/********************************************************************************
** Form generated from reading UI file 'p23_chargebymoney.ui'
**
** Created: Sat Jan 3 11:22:06 2015
**      by: Qt User Interface Compiler version 4.8.4
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_P23_CHARGEBYMONEY_H
#define UI_P23_CHARGEBYMONEY_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QDialog>
#include <QtGui/QFrame>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QLineEdit>
#include <QtGui/QPushButton>

QT_BEGIN_NAMESPACE

class Ui_p23_chargebymoney
{
public:
    QFrame *frame_4;
    QLabel *label_phone;
    QLabel *label_phone_2;
    QLabel *lbl_speaker;
    QFrame *frame_3;
    QPushButton *pbtn_num0;
    QPushButton *pbtn_num1;
    QPushButton *pbtn_num2;
    QPushButton *pbtn_num5;
    QPushButton *pbtn_num3;
    QPushButton *pbtn_num4;
    QPushButton *pbtn_num6;
    QPushButton *pbtn_back;
    QPushButton *pbtn_num7;
    QPushButton *pbtn_dot;
    QPushButton *pbtn_num8;
    QPushButton *pbtn_num9;
    QPushButton *pbtn_ok;
    QPushButton *pbtn_go;
    QLabel *label_logo;
    QLabel *label_stubnum;
    QLineEdit *lbl_time_chose;
    QLabel *label_2;
    QPushButton *pbtn_180min;
    QPushButton *pbtn_60min;
    QPushButton *pbtn_30min;
    QPushButton *pbtn_120min;
    QLabel *label_code;

    void setupUi(QDialog *p23_chargebymoney)
    {
        if (p23_chargebymoney->objectName().isEmpty())
            p23_chargebymoney->setObjectName(QString::fromUtf8("p23_chargebymoney"));
        p23_chargebymoney->resize(800, 480);
        frame_4 = new QFrame(p23_chargebymoney);
        frame_4->setObjectName(QString::fromUtf8("frame_4"));
        frame_4->setGeometry(QRect(0, 0, 800, 480));
        frame_4->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/PICS/backgroud_1.png);"));
        frame_4->setFrameShape(QFrame::StyledPanel);
        frame_4->setFrameShadow(QFrame::Raised);
        label_phone = new QLabel(frame_4);
        label_phone->setObjectName(QString::fromUtf8("label_phone"));
        label_phone->setGeometry(QRect(460, 460, 171, 20));
        QPalette palette;
        QBrush brush(QColor(255, 255, 255, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush1(QColor(14, 14, 242, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Button, brush1);
        QBrush brush2(QColor(123, 123, 255, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Light, brush2);
        QBrush brush3(QColor(68, 68, 248, 255));
        brush3.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        QBrush brush4(QColor(7, 7, 121, 255));
        brush4.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Dark, brush4);
        QBrush brush5(QColor(9, 9, 161, 255));
        brush5.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Mid, brush5);
        QBrush brush6(QColor(0, 0, 0, 255));
        brush6.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Text, brush6);
        palette.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette.setBrush(QPalette::Active, QPalette::ButtonText, brush6);
        palette.setBrush(QPalette::Active, QPalette::Base, brush);
        palette.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette.setBrush(QPalette::Active, QPalette::Shadow, brush6);
        QBrush brush7(QColor(134, 134, 248, 255));
        brush7.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::AlternateBase, brush7);
        QBrush brush8(QColor(255, 255, 220, 255));
        brush8.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette.setBrush(QPalette::Active, QPalette::ToolTipText, brush6);
        palette.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Inactive, QPalette::Text, brush6);
        palette.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::ButtonText, brush6);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Shadow, brush6);
        palette.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush7);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush6);
        palette.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Shadow, brush6);
        palette.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush6);
        label_phone->setPalette(palette);
        QFont font;
        font.setPointSize(20);
        font.setBold(true);
        font.setWeight(75);
        label_phone->setFont(font);
        label_phone->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/mainlab_phonenum.png);"));
        label_phone->setTextFormat(Qt::AutoText);
        label_phone_2 = new QLabel(frame_4);
        label_phone_2->setObjectName(QString::fromUtf8("label_phone_2"));
        label_phone_2->setGeometry(QRect(625, 460, 171, 20));
        QPalette palette1;
        palette1.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette1.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette1.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette1.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        palette1.setBrush(QPalette::Active, QPalette::Dark, brush4);
        palette1.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette1.setBrush(QPalette::Active, QPalette::Text, brush6);
        palette1.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette1.setBrush(QPalette::Active, QPalette::ButtonText, brush6);
        palette1.setBrush(QPalette::Active, QPalette::Base, brush);
        palette1.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette1.setBrush(QPalette::Active, QPalette::Shadow, brush6);
        palette1.setBrush(QPalette::Active, QPalette::AlternateBase, brush7);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipText, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette1.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette1.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette1.setBrush(QPalette::Inactive, QPalette::Text, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::ButtonText, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Shadow, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush7);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush6);
        palette1.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette1.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette1.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette1.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette1.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette1.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette1.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette1.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Shadow, brush6);
        palette1.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush6);
        label_phone_2->setPalette(palette1);
        label_phone_2->setFont(font);
        label_phone_2->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/mainlab_phonenum.png);"));
        label_phone_2->setTextFormat(Qt::AutoText);
        lbl_speaker = new QLabel(frame_4);
        lbl_speaker->setObjectName(QString::fromUtf8("lbl_speaker"));
        lbl_speaker->setGeometry(QRect(30, 90, 741, 41));
        QFont font1;
        font1.setPointSize(35);
        lbl_speaker->setFont(font1);
        lbl_speaker->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/frame_white.png);"));
        lbl_speaker->setAlignment(Qt::AlignCenter);
        frame_3 = new QFrame(frame_4);
        frame_3->setObjectName(QString::fromUtf8("frame_3"));
        frame_3->setGeometry(QRect(37, 210, 731, 171));
        frame_3->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/frame_white.png);"));
        frame_3->setFrameShape(QFrame::StyledPanel);
        frame_3->setFrameShadow(QFrame::Raised);
        pbtn_num0 = new QPushButton(frame_3);
        pbtn_num0->setObjectName(QString::fromUtf8("pbtn_num0"));
        pbtn_num0->setGeometry(QRect(20, 10, 61, 61));
        QPalette palette2;
        palette2.setBrush(QPalette::Active, QPalette::WindowText, brush6);
        QBrush brush9(QColor(170, 255, 0, 255));
        brush9.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Button, brush9);
        QBrush brush10(QColor(213, 255, 127, 255));
        brush10.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Light, brush10);
        QBrush brush11(QColor(191, 255, 63, 255));
        brush11.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Midlight, brush11);
        QBrush brush12(QColor(85, 127, 0, 255));
        brush12.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Dark, brush12);
        QBrush brush13(QColor(113, 170, 0, 255));
        brush13.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Mid, brush13);
        palette2.setBrush(QPalette::Active, QPalette::Text, brush6);
        palette2.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette2.setBrush(QPalette::Active, QPalette::ButtonText, brush6);
        palette2.setBrush(QPalette::Active, QPalette::Base, brush);
        palette2.setBrush(QPalette::Active, QPalette::Window, brush9);
        palette2.setBrush(QPalette::Active, QPalette::Shadow, brush6);
        QBrush brush14(QColor(212, 255, 127, 255));
        brush14.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::AlternateBase, brush14);
        palette2.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette2.setBrush(QPalette::Active, QPalette::ToolTipText, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::WindowText, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::Button, brush9);
        palette2.setBrush(QPalette::Inactive, QPalette::Light, brush10);
        palette2.setBrush(QPalette::Inactive, QPalette::Midlight, brush11);
        palette2.setBrush(QPalette::Inactive, QPalette::Dark, brush12);
        palette2.setBrush(QPalette::Inactive, QPalette::Mid, brush13);
        palette2.setBrush(QPalette::Inactive, QPalette::Text, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::ButtonText, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Window, brush9);
        palette2.setBrush(QPalette::Inactive, QPalette::Shadow, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush14);
        palette2.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette2.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::WindowText, brush12);
        palette2.setBrush(QPalette::Disabled, QPalette::Button, brush9);
        palette2.setBrush(QPalette::Disabled, QPalette::Light, brush10);
        palette2.setBrush(QPalette::Disabled, QPalette::Midlight, brush11);
        palette2.setBrush(QPalette::Disabled, QPalette::Dark, brush12);
        palette2.setBrush(QPalette::Disabled, QPalette::Mid, brush13);
        palette2.setBrush(QPalette::Disabled, QPalette::Text, brush12);
        palette2.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::ButtonText, brush12);
        palette2.setBrush(QPalette::Disabled, QPalette::Base, brush9);
        palette2.setBrush(QPalette::Disabled, QPalette::Window, brush9);
        palette2.setBrush(QPalette::Disabled, QPalette::Shadow, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush9);
        palette2.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette2.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush6);
        pbtn_num0->setPalette(palette2);
        pbtn_num0->setFont(font);
        pbtn_num0->setFocusPolicy(Qt::NoFocus);
        pbtn_num0->setStyleSheet(QString::fromUtf8("border-image: url(:/btn/qrc/PICS/Pbtn.png);"));
        pbtn_num1 = new QPushButton(frame_3);
        pbtn_num1->setObjectName(QString::fromUtf8("pbtn_num1"));
        pbtn_num1->setGeometry(QRect(110, 10, 61, 61));
        QPalette palette3;
        palette3.setBrush(QPalette::Active, QPalette::WindowText, brush6);
        palette3.setBrush(QPalette::Active, QPalette::Button, brush9);
        palette3.setBrush(QPalette::Active, QPalette::Light, brush10);
        palette3.setBrush(QPalette::Active, QPalette::Midlight, brush11);
        palette3.setBrush(QPalette::Active, QPalette::Dark, brush12);
        palette3.setBrush(QPalette::Active, QPalette::Mid, brush13);
        palette3.setBrush(QPalette::Active, QPalette::Text, brush6);
        palette3.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette3.setBrush(QPalette::Active, QPalette::ButtonText, brush6);
        palette3.setBrush(QPalette::Active, QPalette::Base, brush);
        palette3.setBrush(QPalette::Active, QPalette::Window, brush9);
        palette3.setBrush(QPalette::Active, QPalette::Shadow, brush6);
        palette3.setBrush(QPalette::Active, QPalette::AlternateBase, brush14);
        palette3.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette3.setBrush(QPalette::Active, QPalette::ToolTipText, brush6);
        palette3.setBrush(QPalette::Inactive, QPalette::WindowText, brush6);
        palette3.setBrush(QPalette::Inactive, QPalette::Button, brush9);
        palette3.setBrush(QPalette::Inactive, QPalette::Light, brush10);
        palette3.setBrush(QPalette::Inactive, QPalette::Midlight, brush11);
        palette3.setBrush(QPalette::Inactive, QPalette::Dark, brush12);
        palette3.setBrush(QPalette::Inactive, QPalette::Mid, brush13);
        palette3.setBrush(QPalette::Inactive, QPalette::Text, brush6);
        palette3.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::ButtonText, brush6);
        palette3.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Window, brush9);
        palette3.setBrush(QPalette::Inactive, QPalette::Shadow, brush6);
        palette3.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush14);
        palette3.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette3.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush6);
        palette3.setBrush(QPalette::Disabled, QPalette::WindowText, brush12);
        palette3.setBrush(QPalette::Disabled, QPalette::Button, brush9);
        palette3.setBrush(QPalette::Disabled, QPalette::Light, brush10);
        palette3.setBrush(QPalette::Disabled, QPalette::Midlight, brush11);
        palette3.setBrush(QPalette::Disabled, QPalette::Dark, brush12);
        palette3.setBrush(QPalette::Disabled, QPalette::Mid, brush13);
        palette3.setBrush(QPalette::Disabled, QPalette::Text, brush12);
        palette3.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::ButtonText, brush12);
        palette3.setBrush(QPalette::Disabled, QPalette::Base, brush9);
        palette3.setBrush(QPalette::Disabled, QPalette::Window, brush9);
        palette3.setBrush(QPalette::Disabled, QPalette::Shadow, brush6);
        palette3.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush9);
        palette3.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette3.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush6);
        pbtn_num1->setPalette(palette3);
        pbtn_num1->setFont(font);
        pbtn_num1->setFocusPolicy(Qt::NoFocus);
        pbtn_num1->setStyleSheet(QString::fromUtf8("border-image: url(:/btn/qrc/PICS/Pbtn.png);"));
        pbtn_num2 = new QPushButton(frame_3);
        pbtn_num2->setObjectName(QString::fromUtf8("pbtn_num2"));
        pbtn_num2->setGeometry(QRect(200, 10, 61, 61));
        QPalette palette4;
        palette4.setBrush(QPalette::Active, QPalette::WindowText, brush6);
        palette4.setBrush(QPalette::Active, QPalette::Button, brush9);
        palette4.setBrush(QPalette::Active, QPalette::Light, brush10);
        palette4.setBrush(QPalette::Active, QPalette::Midlight, brush11);
        palette4.setBrush(QPalette::Active, QPalette::Dark, brush12);
        palette4.setBrush(QPalette::Active, QPalette::Mid, brush13);
        palette4.setBrush(QPalette::Active, QPalette::Text, brush6);
        palette4.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette4.setBrush(QPalette::Active, QPalette::ButtonText, brush6);
        palette4.setBrush(QPalette::Active, QPalette::Base, brush);
        palette4.setBrush(QPalette::Active, QPalette::Window, brush9);
        palette4.setBrush(QPalette::Active, QPalette::Shadow, brush6);
        palette4.setBrush(QPalette::Active, QPalette::AlternateBase, brush14);
        palette4.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette4.setBrush(QPalette::Active, QPalette::ToolTipText, brush6);
        palette4.setBrush(QPalette::Inactive, QPalette::WindowText, brush6);
        palette4.setBrush(QPalette::Inactive, QPalette::Button, brush9);
        palette4.setBrush(QPalette::Inactive, QPalette::Light, brush10);
        palette4.setBrush(QPalette::Inactive, QPalette::Midlight, brush11);
        palette4.setBrush(QPalette::Inactive, QPalette::Dark, brush12);
        palette4.setBrush(QPalette::Inactive, QPalette::Mid, brush13);
        palette4.setBrush(QPalette::Inactive, QPalette::Text, brush6);
        palette4.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::ButtonText, brush6);
        palette4.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Window, brush9);
        palette4.setBrush(QPalette::Inactive, QPalette::Shadow, brush6);
        palette4.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush14);
        palette4.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette4.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush6);
        palette4.setBrush(QPalette::Disabled, QPalette::WindowText, brush12);
        palette4.setBrush(QPalette::Disabled, QPalette::Button, brush9);
        palette4.setBrush(QPalette::Disabled, QPalette::Light, brush10);
        palette4.setBrush(QPalette::Disabled, QPalette::Midlight, brush11);
        palette4.setBrush(QPalette::Disabled, QPalette::Dark, brush12);
        palette4.setBrush(QPalette::Disabled, QPalette::Mid, brush13);
        palette4.setBrush(QPalette::Disabled, QPalette::Text, brush12);
        palette4.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::ButtonText, brush12);
        palette4.setBrush(QPalette::Disabled, QPalette::Base, brush9);
        palette4.setBrush(QPalette::Disabled, QPalette::Window, brush9);
        palette4.setBrush(QPalette::Disabled, QPalette::Shadow, brush6);
        palette4.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush9);
        palette4.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette4.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush6);
        pbtn_num2->setPalette(palette4);
        pbtn_num2->setFont(font);
        pbtn_num2->setFocusPolicy(Qt::NoFocus);
        pbtn_num2->setStyleSheet(QString::fromUtf8("border-image: url(:/btn/qrc/PICS/Pbtn.png);"));
        pbtn_num5 = new QPushButton(frame_3);
        pbtn_num5->setObjectName(QString::fromUtf8("pbtn_num5"));
        pbtn_num5->setGeometry(QRect(470, 10, 61, 61));
        QPalette palette5;
        palette5.setBrush(QPalette::Active, QPalette::WindowText, brush6);
        palette5.setBrush(QPalette::Active, QPalette::Button, brush9);
        palette5.setBrush(QPalette::Active, QPalette::Light, brush10);
        palette5.setBrush(QPalette::Active, QPalette::Midlight, brush11);
        palette5.setBrush(QPalette::Active, QPalette::Dark, brush12);
        palette5.setBrush(QPalette::Active, QPalette::Mid, brush13);
        palette5.setBrush(QPalette::Active, QPalette::Text, brush6);
        palette5.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette5.setBrush(QPalette::Active, QPalette::ButtonText, brush6);
        palette5.setBrush(QPalette::Active, QPalette::Base, brush);
        palette5.setBrush(QPalette::Active, QPalette::Window, brush9);
        palette5.setBrush(QPalette::Active, QPalette::Shadow, brush6);
        palette5.setBrush(QPalette::Active, QPalette::AlternateBase, brush14);
        palette5.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette5.setBrush(QPalette::Active, QPalette::ToolTipText, brush6);
        palette5.setBrush(QPalette::Inactive, QPalette::WindowText, brush6);
        palette5.setBrush(QPalette::Inactive, QPalette::Button, brush9);
        palette5.setBrush(QPalette::Inactive, QPalette::Light, brush10);
        palette5.setBrush(QPalette::Inactive, QPalette::Midlight, brush11);
        palette5.setBrush(QPalette::Inactive, QPalette::Dark, brush12);
        palette5.setBrush(QPalette::Inactive, QPalette::Mid, brush13);
        palette5.setBrush(QPalette::Inactive, QPalette::Text, brush6);
        palette5.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::ButtonText, brush6);
        palette5.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::Window, brush9);
        palette5.setBrush(QPalette::Inactive, QPalette::Shadow, brush6);
        palette5.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush14);
        palette5.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette5.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush6);
        palette5.setBrush(QPalette::Disabled, QPalette::WindowText, brush12);
        palette5.setBrush(QPalette::Disabled, QPalette::Button, brush9);
        palette5.setBrush(QPalette::Disabled, QPalette::Light, brush10);
        palette5.setBrush(QPalette::Disabled, QPalette::Midlight, brush11);
        palette5.setBrush(QPalette::Disabled, QPalette::Dark, brush12);
        palette5.setBrush(QPalette::Disabled, QPalette::Mid, brush13);
        palette5.setBrush(QPalette::Disabled, QPalette::Text, brush12);
        palette5.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette5.setBrush(QPalette::Disabled, QPalette::ButtonText, brush12);
        palette5.setBrush(QPalette::Disabled, QPalette::Base, brush9);
        palette5.setBrush(QPalette::Disabled, QPalette::Window, brush9);
        palette5.setBrush(QPalette::Disabled, QPalette::Shadow, brush6);
        palette5.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush9);
        palette5.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette5.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush6);
        pbtn_num5->setPalette(palette5);
        pbtn_num5->setFont(font);
        pbtn_num5->setFocusPolicy(Qt::NoFocus);
        pbtn_num5->setStyleSheet(QString::fromUtf8("border-image: url(:/btn/qrc/PICS/Pbtn.png);"));
        pbtn_num3 = new QPushButton(frame_3);
        pbtn_num3->setObjectName(QString::fromUtf8("pbtn_num3"));
        pbtn_num3->setGeometry(QRect(290, 10, 61, 61));
        QPalette palette6;
        palette6.setBrush(QPalette::Active, QPalette::WindowText, brush6);
        palette6.setBrush(QPalette::Active, QPalette::Button, brush9);
        palette6.setBrush(QPalette::Active, QPalette::Light, brush10);
        palette6.setBrush(QPalette::Active, QPalette::Midlight, brush11);
        palette6.setBrush(QPalette::Active, QPalette::Dark, brush12);
        palette6.setBrush(QPalette::Active, QPalette::Mid, brush13);
        palette6.setBrush(QPalette::Active, QPalette::Text, brush6);
        palette6.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette6.setBrush(QPalette::Active, QPalette::ButtonText, brush6);
        palette6.setBrush(QPalette::Active, QPalette::Base, brush);
        palette6.setBrush(QPalette::Active, QPalette::Window, brush9);
        palette6.setBrush(QPalette::Active, QPalette::Shadow, brush6);
        palette6.setBrush(QPalette::Active, QPalette::AlternateBase, brush14);
        palette6.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette6.setBrush(QPalette::Active, QPalette::ToolTipText, brush6);
        palette6.setBrush(QPalette::Inactive, QPalette::WindowText, brush6);
        palette6.setBrush(QPalette::Inactive, QPalette::Button, brush9);
        palette6.setBrush(QPalette::Inactive, QPalette::Light, brush10);
        palette6.setBrush(QPalette::Inactive, QPalette::Midlight, brush11);
        palette6.setBrush(QPalette::Inactive, QPalette::Dark, brush12);
        palette6.setBrush(QPalette::Inactive, QPalette::Mid, brush13);
        palette6.setBrush(QPalette::Inactive, QPalette::Text, brush6);
        palette6.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::ButtonText, brush6);
        palette6.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::Window, brush9);
        palette6.setBrush(QPalette::Inactive, QPalette::Shadow, brush6);
        palette6.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush14);
        palette6.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette6.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush6);
        palette6.setBrush(QPalette::Disabled, QPalette::WindowText, brush12);
        palette6.setBrush(QPalette::Disabled, QPalette::Button, brush9);
        palette6.setBrush(QPalette::Disabled, QPalette::Light, brush10);
        palette6.setBrush(QPalette::Disabled, QPalette::Midlight, brush11);
        palette6.setBrush(QPalette::Disabled, QPalette::Dark, brush12);
        palette6.setBrush(QPalette::Disabled, QPalette::Mid, brush13);
        palette6.setBrush(QPalette::Disabled, QPalette::Text, brush12);
        palette6.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette6.setBrush(QPalette::Disabled, QPalette::ButtonText, brush12);
        palette6.setBrush(QPalette::Disabled, QPalette::Base, brush9);
        palette6.setBrush(QPalette::Disabled, QPalette::Window, brush9);
        palette6.setBrush(QPalette::Disabled, QPalette::Shadow, brush6);
        palette6.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush9);
        palette6.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette6.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush6);
        pbtn_num3->setPalette(palette6);
        pbtn_num3->setFont(font);
        pbtn_num3->setFocusPolicy(Qt::NoFocus);
        pbtn_num3->setStyleSheet(QString::fromUtf8("border-image: url(:/btn/qrc/PICS/Pbtn.png);"));
        pbtn_num4 = new QPushButton(frame_3);
        pbtn_num4->setObjectName(QString::fromUtf8("pbtn_num4"));
        pbtn_num4->setGeometry(QRect(380, 10, 61, 61));
        QPalette palette7;
        palette7.setBrush(QPalette::Active, QPalette::WindowText, brush6);
        palette7.setBrush(QPalette::Active, QPalette::Button, brush9);
        palette7.setBrush(QPalette::Active, QPalette::Light, brush10);
        palette7.setBrush(QPalette::Active, QPalette::Midlight, brush11);
        palette7.setBrush(QPalette::Active, QPalette::Dark, brush12);
        palette7.setBrush(QPalette::Active, QPalette::Mid, brush13);
        palette7.setBrush(QPalette::Active, QPalette::Text, brush6);
        palette7.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette7.setBrush(QPalette::Active, QPalette::ButtonText, brush6);
        palette7.setBrush(QPalette::Active, QPalette::Base, brush);
        palette7.setBrush(QPalette::Active, QPalette::Window, brush9);
        palette7.setBrush(QPalette::Active, QPalette::Shadow, brush6);
        palette7.setBrush(QPalette::Active, QPalette::AlternateBase, brush14);
        palette7.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette7.setBrush(QPalette::Active, QPalette::ToolTipText, brush6);
        palette7.setBrush(QPalette::Inactive, QPalette::WindowText, brush6);
        palette7.setBrush(QPalette::Inactive, QPalette::Button, brush9);
        palette7.setBrush(QPalette::Inactive, QPalette::Light, brush10);
        palette7.setBrush(QPalette::Inactive, QPalette::Midlight, brush11);
        palette7.setBrush(QPalette::Inactive, QPalette::Dark, brush12);
        palette7.setBrush(QPalette::Inactive, QPalette::Mid, brush13);
        palette7.setBrush(QPalette::Inactive, QPalette::Text, brush6);
        palette7.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::ButtonText, brush6);
        palette7.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::Window, brush9);
        palette7.setBrush(QPalette::Inactive, QPalette::Shadow, brush6);
        palette7.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush14);
        palette7.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette7.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush6);
        palette7.setBrush(QPalette::Disabled, QPalette::WindowText, brush12);
        palette7.setBrush(QPalette::Disabled, QPalette::Button, brush9);
        palette7.setBrush(QPalette::Disabled, QPalette::Light, brush10);
        palette7.setBrush(QPalette::Disabled, QPalette::Midlight, brush11);
        palette7.setBrush(QPalette::Disabled, QPalette::Dark, brush12);
        palette7.setBrush(QPalette::Disabled, QPalette::Mid, brush13);
        palette7.setBrush(QPalette::Disabled, QPalette::Text, brush12);
        palette7.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette7.setBrush(QPalette::Disabled, QPalette::ButtonText, brush12);
        palette7.setBrush(QPalette::Disabled, QPalette::Base, brush9);
        palette7.setBrush(QPalette::Disabled, QPalette::Window, brush9);
        palette7.setBrush(QPalette::Disabled, QPalette::Shadow, brush6);
        palette7.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush9);
        palette7.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette7.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush6);
        pbtn_num4->setPalette(palette7);
        pbtn_num4->setFont(font);
        pbtn_num4->setFocusPolicy(Qt::NoFocus);
        pbtn_num4->setStyleSheet(QString::fromUtf8("border-image: url(:/btn/qrc/PICS/Pbtn.png);"));
        pbtn_num6 = new QPushButton(frame_3);
        pbtn_num6->setObjectName(QString::fromUtf8("pbtn_num6"));
        pbtn_num6->setGeometry(QRect(560, 10, 61, 61));
        QPalette palette8;
        palette8.setBrush(QPalette::Active, QPalette::WindowText, brush6);
        palette8.setBrush(QPalette::Active, QPalette::Button, brush9);
        palette8.setBrush(QPalette::Active, QPalette::Light, brush10);
        palette8.setBrush(QPalette::Active, QPalette::Midlight, brush11);
        palette8.setBrush(QPalette::Active, QPalette::Dark, brush12);
        palette8.setBrush(QPalette::Active, QPalette::Mid, brush13);
        palette8.setBrush(QPalette::Active, QPalette::Text, brush6);
        palette8.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette8.setBrush(QPalette::Active, QPalette::ButtonText, brush6);
        palette8.setBrush(QPalette::Active, QPalette::Base, brush);
        palette8.setBrush(QPalette::Active, QPalette::Window, brush9);
        palette8.setBrush(QPalette::Active, QPalette::Shadow, brush6);
        palette8.setBrush(QPalette::Active, QPalette::AlternateBase, brush14);
        palette8.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette8.setBrush(QPalette::Active, QPalette::ToolTipText, brush6);
        palette8.setBrush(QPalette::Inactive, QPalette::WindowText, brush6);
        palette8.setBrush(QPalette::Inactive, QPalette::Button, brush9);
        palette8.setBrush(QPalette::Inactive, QPalette::Light, brush10);
        palette8.setBrush(QPalette::Inactive, QPalette::Midlight, brush11);
        palette8.setBrush(QPalette::Inactive, QPalette::Dark, brush12);
        palette8.setBrush(QPalette::Inactive, QPalette::Mid, brush13);
        palette8.setBrush(QPalette::Inactive, QPalette::Text, brush6);
        palette8.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::ButtonText, brush6);
        palette8.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::Window, brush9);
        palette8.setBrush(QPalette::Inactive, QPalette::Shadow, brush6);
        palette8.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush14);
        palette8.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette8.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush6);
        palette8.setBrush(QPalette::Disabled, QPalette::WindowText, brush12);
        palette8.setBrush(QPalette::Disabled, QPalette::Button, brush9);
        palette8.setBrush(QPalette::Disabled, QPalette::Light, brush10);
        palette8.setBrush(QPalette::Disabled, QPalette::Midlight, brush11);
        palette8.setBrush(QPalette::Disabled, QPalette::Dark, brush12);
        palette8.setBrush(QPalette::Disabled, QPalette::Mid, brush13);
        palette8.setBrush(QPalette::Disabled, QPalette::Text, brush12);
        palette8.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette8.setBrush(QPalette::Disabled, QPalette::ButtonText, brush12);
        palette8.setBrush(QPalette::Disabled, QPalette::Base, brush9);
        palette8.setBrush(QPalette::Disabled, QPalette::Window, brush9);
        palette8.setBrush(QPalette::Disabled, QPalette::Shadow, brush6);
        palette8.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush9);
        palette8.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette8.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush6);
        pbtn_num6->setPalette(palette8);
        pbtn_num6->setFont(font);
        pbtn_num6->setFocusPolicy(Qt::NoFocus);
        pbtn_num6->setStyleSheet(QString::fromUtf8("border-image: url(:/btn/qrc/PICS/Pbtn.png);"));
        pbtn_back = new QPushButton(frame_3);
        pbtn_back->setObjectName(QString::fromUtf8("pbtn_back"));
        pbtn_back->setGeometry(QRect(389, 100, 61, 61));
        QPalette palette9;
        palette9.setBrush(QPalette::Active, QPalette::WindowText, brush6);
        palette9.setBrush(QPalette::Active, QPalette::Button, brush9);
        palette9.setBrush(QPalette::Active, QPalette::Light, brush10);
        palette9.setBrush(QPalette::Active, QPalette::Midlight, brush11);
        palette9.setBrush(QPalette::Active, QPalette::Dark, brush12);
        palette9.setBrush(QPalette::Active, QPalette::Mid, brush13);
        palette9.setBrush(QPalette::Active, QPalette::Text, brush6);
        palette9.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette9.setBrush(QPalette::Active, QPalette::ButtonText, brush6);
        palette9.setBrush(QPalette::Active, QPalette::Base, brush);
        palette9.setBrush(QPalette::Active, QPalette::Window, brush9);
        palette9.setBrush(QPalette::Active, QPalette::Shadow, brush6);
        palette9.setBrush(QPalette::Active, QPalette::AlternateBase, brush14);
        palette9.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette9.setBrush(QPalette::Active, QPalette::ToolTipText, brush6);
        palette9.setBrush(QPalette::Inactive, QPalette::WindowText, brush6);
        palette9.setBrush(QPalette::Inactive, QPalette::Button, brush9);
        palette9.setBrush(QPalette::Inactive, QPalette::Light, brush10);
        palette9.setBrush(QPalette::Inactive, QPalette::Midlight, brush11);
        palette9.setBrush(QPalette::Inactive, QPalette::Dark, brush12);
        palette9.setBrush(QPalette::Inactive, QPalette::Mid, brush13);
        palette9.setBrush(QPalette::Inactive, QPalette::Text, brush6);
        palette9.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::ButtonText, brush6);
        palette9.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::Window, brush9);
        palette9.setBrush(QPalette::Inactive, QPalette::Shadow, brush6);
        palette9.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush14);
        palette9.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette9.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush6);
        palette9.setBrush(QPalette::Disabled, QPalette::WindowText, brush12);
        palette9.setBrush(QPalette::Disabled, QPalette::Button, brush9);
        palette9.setBrush(QPalette::Disabled, QPalette::Light, brush10);
        palette9.setBrush(QPalette::Disabled, QPalette::Midlight, brush11);
        palette9.setBrush(QPalette::Disabled, QPalette::Dark, brush12);
        palette9.setBrush(QPalette::Disabled, QPalette::Mid, brush13);
        palette9.setBrush(QPalette::Disabled, QPalette::Text, brush12);
        palette9.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette9.setBrush(QPalette::Disabled, QPalette::ButtonText, brush12);
        palette9.setBrush(QPalette::Disabled, QPalette::Base, brush9);
        palette9.setBrush(QPalette::Disabled, QPalette::Window, brush9);
        palette9.setBrush(QPalette::Disabled, QPalette::Shadow, brush6);
        palette9.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush9);
        palette9.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette9.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush6);
        pbtn_back->setPalette(palette9);
        pbtn_back->setFont(font);
        pbtn_back->setFocusPolicy(Qt::NoFocus);
        pbtn_back->setStyleSheet(QString::fromUtf8("border-image: url(:/btn/qrc/PICS/Pbtn.png);"));
        pbtn_num7 = new QPushButton(frame_3);
        pbtn_num7->setObjectName(QString::fromUtf8("pbtn_num7"));
        pbtn_num7->setGeometry(QRect(650, 10, 61, 61));
        QPalette palette10;
        palette10.setBrush(QPalette::Active, QPalette::WindowText, brush6);
        palette10.setBrush(QPalette::Active, QPalette::Button, brush9);
        palette10.setBrush(QPalette::Active, QPalette::Light, brush10);
        palette10.setBrush(QPalette::Active, QPalette::Midlight, brush11);
        palette10.setBrush(QPalette::Active, QPalette::Dark, brush12);
        palette10.setBrush(QPalette::Active, QPalette::Mid, brush13);
        palette10.setBrush(QPalette::Active, QPalette::Text, brush6);
        palette10.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette10.setBrush(QPalette::Active, QPalette::ButtonText, brush6);
        palette10.setBrush(QPalette::Active, QPalette::Base, brush);
        palette10.setBrush(QPalette::Active, QPalette::Window, brush9);
        palette10.setBrush(QPalette::Active, QPalette::Shadow, brush6);
        palette10.setBrush(QPalette::Active, QPalette::AlternateBase, brush14);
        palette10.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette10.setBrush(QPalette::Active, QPalette::ToolTipText, brush6);
        palette10.setBrush(QPalette::Inactive, QPalette::WindowText, brush6);
        palette10.setBrush(QPalette::Inactive, QPalette::Button, brush9);
        palette10.setBrush(QPalette::Inactive, QPalette::Light, brush10);
        palette10.setBrush(QPalette::Inactive, QPalette::Midlight, brush11);
        palette10.setBrush(QPalette::Inactive, QPalette::Dark, brush12);
        palette10.setBrush(QPalette::Inactive, QPalette::Mid, brush13);
        palette10.setBrush(QPalette::Inactive, QPalette::Text, brush6);
        palette10.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette10.setBrush(QPalette::Inactive, QPalette::ButtonText, brush6);
        palette10.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette10.setBrush(QPalette::Inactive, QPalette::Window, brush9);
        palette10.setBrush(QPalette::Inactive, QPalette::Shadow, brush6);
        palette10.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush14);
        palette10.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette10.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush6);
        palette10.setBrush(QPalette::Disabled, QPalette::WindowText, brush12);
        palette10.setBrush(QPalette::Disabled, QPalette::Button, brush9);
        palette10.setBrush(QPalette::Disabled, QPalette::Light, brush10);
        palette10.setBrush(QPalette::Disabled, QPalette::Midlight, brush11);
        palette10.setBrush(QPalette::Disabled, QPalette::Dark, brush12);
        palette10.setBrush(QPalette::Disabled, QPalette::Mid, brush13);
        palette10.setBrush(QPalette::Disabled, QPalette::Text, brush12);
        palette10.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette10.setBrush(QPalette::Disabled, QPalette::ButtonText, brush12);
        palette10.setBrush(QPalette::Disabled, QPalette::Base, brush9);
        palette10.setBrush(QPalette::Disabled, QPalette::Window, brush9);
        palette10.setBrush(QPalette::Disabled, QPalette::Shadow, brush6);
        palette10.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush9);
        palette10.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette10.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush6);
        pbtn_num7->setPalette(palette10);
        pbtn_num7->setFont(font);
        pbtn_num7->setFocusPolicy(Qt::NoFocus);
        pbtn_num7->setStyleSheet(QString::fromUtf8("border-image: url(:/btn/qrc/PICS/Pbtn.png);"));
        pbtn_dot = new QPushButton(frame_3);
        pbtn_dot->setObjectName(QString::fromUtf8("pbtn_dot"));
        pbtn_dot->setGeometry(QRect(279, 100, 61, 61));
        QPalette palette11;
        palette11.setBrush(QPalette::Active, QPalette::WindowText, brush6);
        palette11.setBrush(QPalette::Active, QPalette::Button, brush9);
        palette11.setBrush(QPalette::Active, QPalette::Light, brush10);
        palette11.setBrush(QPalette::Active, QPalette::Midlight, brush11);
        palette11.setBrush(QPalette::Active, QPalette::Dark, brush12);
        palette11.setBrush(QPalette::Active, QPalette::Mid, brush13);
        palette11.setBrush(QPalette::Active, QPalette::Text, brush6);
        palette11.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette11.setBrush(QPalette::Active, QPalette::ButtonText, brush6);
        palette11.setBrush(QPalette::Active, QPalette::Base, brush);
        palette11.setBrush(QPalette::Active, QPalette::Window, brush9);
        palette11.setBrush(QPalette::Active, QPalette::Shadow, brush6);
        palette11.setBrush(QPalette::Active, QPalette::AlternateBase, brush14);
        palette11.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette11.setBrush(QPalette::Active, QPalette::ToolTipText, brush6);
        palette11.setBrush(QPalette::Inactive, QPalette::WindowText, brush6);
        palette11.setBrush(QPalette::Inactive, QPalette::Button, brush9);
        palette11.setBrush(QPalette::Inactive, QPalette::Light, brush10);
        palette11.setBrush(QPalette::Inactive, QPalette::Midlight, brush11);
        palette11.setBrush(QPalette::Inactive, QPalette::Dark, brush12);
        palette11.setBrush(QPalette::Inactive, QPalette::Mid, brush13);
        palette11.setBrush(QPalette::Inactive, QPalette::Text, brush6);
        palette11.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette11.setBrush(QPalette::Inactive, QPalette::ButtonText, brush6);
        palette11.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette11.setBrush(QPalette::Inactive, QPalette::Window, brush9);
        palette11.setBrush(QPalette::Inactive, QPalette::Shadow, brush6);
        palette11.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush14);
        palette11.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette11.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush6);
        palette11.setBrush(QPalette::Disabled, QPalette::WindowText, brush12);
        palette11.setBrush(QPalette::Disabled, QPalette::Button, brush9);
        palette11.setBrush(QPalette::Disabled, QPalette::Light, brush10);
        palette11.setBrush(QPalette::Disabled, QPalette::Midlight, brush11);
        palette11.setBrush(QPalette::Disabled, QPalette::Dark, brush12);
        palette11.setBrush(QPalette::Disabled, QPalette::Mid, brush13);
        palette11.setBrush(QPalette::Disabled, QPalette::Text, brush12);
        palette11.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette11.setBrush(QPalette::Disabled, QPalette::ButtonText, brush12);
        palette11.setBrush(QPalette::Disabled, QPalette::Base, brush9);
        palette11.setBrush(QPalette::Disabled, QPalette::Window, brush9);
        palette11.setBrush(QPalette::Disabled, QPalette::Shadow, brush6);
        palette11.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush9);
        palette11.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette11.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush6);
        pbtn_dot->setPalette(palette11);
        pbtn_dot->setFont(font);
        pbtn_dot->setFocusPolicy(Qt::NoFocus);
        pbtn_dot->setStyleSheet(QString::fromUtf8("border-image: url(:/btn/qrc/PICS/Pbtn.png);"));
        pbtn_num8 = new QPushButton(frame_3);
        pbtn_num8->setObjectName(QString::fromUtf8("pbtn_num8"));
        pbtn_num8->setGeometry(QRect(59, 100, 61, 61));
        QPalette palette12;
        palette12.setBrush(QPalette::Active, QPalette::WindowText, brush6);
        palette12.setBrush(QPalette::Active, QPalette::Button, brush9);
        palette12.setBrush(QPalette::Active, QPalette::Light, brush10);
        palette12.setBrush(QPalette::Active, QPalette::Midlight, brush11);
        palette12.setBrush(QPalette::Active, QPalette::Dark, brush12);
        palette12.setBrush(QPalette::Active, QPalette::Mid, brush13);
        palette12.setBrush(QPalette::Active, QPalette::Text, brush6);
        palette12.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette12.setBrush(QPalette::Active, QPalette::ButtonText, brush6);
        palette12.setBrush(QPalette::Active, QPalette::Base, brush);
        palette12.setBrush(QPalette::Active, QPalette::Window, brush9);
        palette12.setBrush(QPalette::Active, QPalette::Shadow, brush6);
        palette12.setBrush(QPalette::Active, QPalette::AlternateBase, brush14);
        palette12.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette12.setBrush(QPalette::Active, QPalette::ToolTipText, brush6);
        palette12.setBrush(QPalette::Inactive, QPalette::WindowText, brush6);
        palette12.setBrush(QPalette::Inactive, QPalette::Button, brush9);
        palette12.setBrush(QPalette::Inactive, QPalette::Light, brush10);
        palette12.setBrush(QPalette::Inactive, QPalette::Midlight, brush11);
        palette12.setBrush(QPalette::Inactive, QPalette::Dark, brush12);
        palette12.setBrush(QPalette::Inactive, QPalette::Mid, brush13);
        palette12.setBrush(QPalette::Inactive, QPalette::Text, brush6);
        palette12.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette12.setBrush(QPalette::Inactive, QPalette::ButtonText, brush6);
        palette12.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette12.setBrush(QPalette::Inactive, QPalette::Window, brush9);
        palette12.setBrush(QPalette::Inactive, QPalette::Shadow, brush6);
        palette12.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush14);
        palette12.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette12.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush6);
        palette12.setBrush(QPalette::Disabled, QPalette::WindowText, brush12);
        palette12.setBrush(QPalette::Disabled, QPalette::Button, brush9);
        palette12.setBrush(QPalette::Disabled, QPalette::Light, brush10);
        palette12.setBrush(QPalette::Disabled, QPalette::Midlight, brush11);
        palette12.setBrush(QPalette::Disabled, QPalette::Dark, brush12);
        palette12.setBrush(QPalette::Disabled, QPalette::Mid, brush13);
        palette12.setBrush(QPalette::Disabled, QPalette::Text, brush12);
        palette12.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette12.setBrush(QPalette::Disabled, QPalette::ButtonText, brush12);
        palette12.setBrush(QPalette::Disabled, QPalette::Base, brush9);
        palette12.setBrush(QPalette::Disabled, QPalette::Window, brush9);
        palette12.setBrush(QPalette::Disabled, QPalette::Shadow, brush6);
        palette12.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush9);
        palette12.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette12.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush6);
        pbtn_num8->setPalette(palette12);
        pbtn_num8->setFont(font);
        pbtn_num8->setFocusPolicy(Qt::NoFocus);
        pbtn_num8->setStyleSheet(QString::fromUtf8("border-image: url(:/btn/qrc/PICS/Pbtn.png);"));
        pbtn_num9 = new QPushButton(frame_3);
        pbtn_num9->setObjectName(QString::fromUtf8("pbtn_num9"));
        pbtn_num9->setGeometry(QRect(169, 100, 61, 61));
        QPalette palette13;
        palette13.setBrush(QPalette::Active, QPalette::WindowText, brush6);
        palette13.setBrush(QPalette::Active, QPalette::Button, brush9);
        palette13.setBrush(QPalette::Active, QPalette::Light, brush10);
        palette13.setBrush(QPalette::Active, QPalette::Midlight, brush11);
        palette13.setBrush(QPalette::Active, QPalette::Dark, brush12);
        palette13.setBrush(QPalette::Active, QPalette::Mid, brush13);
        palette13.setBrush(QPalette::Active, QPalette::Text, brush6);
        palette13.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette13.setBrush(QPalette::Active, QPalette::ButtonText, brush6);
        palette13.setBrush(QPalette::Active, QPalette::Base, brush);
        palette13.setBrush(QPalette::Active, QPalette::Window, brush9);
        palette13.setBrush(QPalette::Active, QPalette::Shadow, brush6);
        palette13.setBrush(QPalette::Active, QPalette::AlternateBase, brush14);
        palette13.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette13.setBrush(QPalette::Active, QPalette::ToolTipText, brush6);
        palette13.setBrush(QPalette::Inactive, QPalette::WindowText, brush6);
        palette13.setBrush(QPalette::Inactive, QPalette::Button, brush9);
        palette13.setBrush(QPalette::Inactive, QPalette::Light, brush10);
        palette13.setBrush(QPalette::Inactive, QPalette::Midlight, brush11);
        palette13.setBrush(QPalette::Inactive, QPalette::Dark, brush12);
        palette13.setBrush(QPalette::Inactive, QPalette::Mid, brush13);
        palette13.setBrush(QPalette::Inactive, QPalette::Text, brush6);
        palette13.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette13.setBrush(QPalette::Inactive, QPalette::ButtonText, brush6);
        palette13.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette13.setBrush(QPalette::Inactive, QPalette::Window, brush9);
        palette13.setBrush(QPalette::Inactive, QPalette::Shadow, brush6);
        palette13.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush14);
        palette13.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette13.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush6);
        palette13.setBrush(QPalette::Disabled, QPalette::WindowText, brush12);
        palette13.setBrush(QPalette::Disabled, QPalette::Button, brush9);
        palette13.setBrush(QPalette::Disabled, QPalette::Light, brush10);
        palette13.setBrush(QPalette::Disabled, QPalette::Midlight, brush11);
        palette13.setBrush(QPalette::Disabled, QPalette::Dark, brush12);
        palette13.setBrush(QPalette::Disabled, QPalette::Mid, brush13);
        palette13.setBrush(QPalette::Disabled, QPalette::Text, brush12);
        palette13.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette13.setBrush(QPalette::Disabled, QPalette::ButtonText, brush12);
        palette13.setBrush(QPalette::Disabled, QPalette::Base, brush9);
        palette13.setBrush(QPalette::Disabled, QPalette::Window, brush9);
        palette13.setBrush(QPalette::Disabled, QPalette::Shadow, brush6);
        palette13.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush9);
        palette13.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette13.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush6);
        pbtn_num9->setPalette(palette13);
        pbtn_num9->setFont(font);
        pbtn_num9->setFocusPolicy(Qt::NoFocus);
        pbtn_num9->setStyleSheet(QString::fromUtf8("border-image: url(:/btn/qrc/PICS/Pbtn.png);"));
        pbtn_ok = new QPushButton(frame_3);
        pbtn_ok->setObjectName(QString::fromUtf8("pbtn_ok"));
        pbtn_ok->setGeometry(QRect(609, 100, 61, 61));
        QPalette palette14;
        palette14.setBrush(QPalette::Active, QPalette::WindowText, brush6);
        palette14.setBrush(QPalette::Active, QPalette::Button, brush9);
        palette14.setBrush(QPalette::Active, QPalette::Light, brush10);
        palette14.setBrush(QPalette::Active, QPalette::Midlight, brush11);
        palette14.setBrush(QPalette::Active, QPalette::Dark, brush12);
        palette14.setBrush(QPalette::Active, QPalette::Mid, brush13);
        palette14.setBrush(QPalette::Active, QPalette::Text, brush6);
        palette14.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette14.setBrush(QPalette::Active, QPalette::ButtonText, brush6);
        palette14.setBrush(QPalette::Active, QPalette::Base, brush);
        palette14.setBrush(QPalette::Active, QPalette::Window, brush9);
        palette14.setBrush(QPalette::Active, QPalette::Shadow, brush6);
        palette14.setBrush(QPalette::Active, QPalette::AlternateBase, brush14);
        palette14.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette14.setBrush(QPalette::Active, QPalette::ToolTipText, brush6);
        palette14.setBrush(QPalette::Inactive, QPalette::WindowText, brush6);
        palette14.setBrush(QPalette::Inactive, QPalette::Button, brush9);
        palette14.setBrush(QPalette::Inactive, QPalette::Light, brush10);
        palette14.setBrush(QPalette::Inactive, QPalette::Midlight, brush11);
        palette14.setBrush(QPalette::Inactive, QPalette::Dark, brush12);
        palette14.setBrush(QPalette::Inactive, QPalette::Mid, brush13);
        palette14.setBrush(QPalette::Inactive, QPalette::Text, brush6);
        palette14.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette14.setBrush(QPalette::Inactive, QPalette::ButtonText, brush6);
        palette14.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette14.setBrush(QPalette::Inactive, QPalette::Window, brush9);
        palette14.setBrush(QPalette::Inactive, QPalette::Shadow, brush6);
        palette14.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush14);
        palette14.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette14.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush6);
        palette14.setBrush(QPalette::Disabled, QPalette::WindowText, brush12);
        palette14.setBrush(QPalette::Disabled, QPalette::Button, brush9);
        palette14.setBrush(QPalette::Disabled, QPalette::Light, brush10);
        palette14.setBrush(QPalette::Disabled, QPalette::Midlight, brush11);
        palette14.setBrush(QPalette::Disabled, QPalette::Dark, brush12);
        palette14.setBrush(QPalette::Disabled, QPalette::Mid, brush13);
        palette14.setBrush(QPalette::Disabled, QPalette::Text, brush12);
        palette14.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette14.setBrush(QPalette::Disabled, QPalette::ButtonText, brush12);
        palette14.setBrush(QPalette::Disabled, QPalette::Base, brush9);
        palette14.setBrush(QPalette::Disabled, QPalette::Window, brush9);
        palette14.setBrush(QPalette::Disabled, QPalette::Shadow, brush6);
        palette14.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush9);
        palette14.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette14.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush6);
        pbtn_ok->setPalette(palette14);
        pbtn_ok->setFont(font);
        pbtn_ok->setFocusPolicy(Qt::NoFocus);
        pbtn_ok->setStyleSheet(QString::fromUtf8("border-image: url(:/btn/qrc/PICS/Pbtn.png);"));
        pbtn_go = new QPushButton(frame_3);
        pbtn_go->setObjectName(QString::fromUtf8("pbtn_go"));
        pbtn_go->setGeometry(QRect(499, 100, 61, 61));
        QPalette palette15;
        palette15.setBrush(QPalette::Active, QPalette::WindowText, brush6);
        palette15.setBrush(QPalette::Active, QPalette::Button, brush9);
        palette15.setBrush(QPalette::Active, QPalette::Light, brush10);
        palette15.setBrush(QPalette::Active, QPalette::Midlight, brush11);
        palette15.setBrush(QPalette::Active, QPalette::Dark, brush12);
        palette15.setBrush(QPalette::Active, QPalette::Mid, brush13);
        palette15.setBrush(QPalette::Active, QPalette::Text, brush6);
        palette15.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette15.setBrush(QPalette::Active, QPalette::ButtonText, brush6);
        palette15.setBrush(QPalette::Active, QPalette::Base, brush);
        palette15.setBrush(QPalette::Active, QPalette::Window, brush9);
        palette15.setBrush(QPalette::Active, QPalette::Shadow, brush6);
        palette15.setBrush(QPalette::Active, QPalette::AlternateBase, brush14);
        palette15.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette15.setBrush(QPalette::Active, QPalette::ToolTipText, brush6);
        palette15.setBrush(QPalette::Inactive, QPalette::WindowText, brush6);
        palette15.setBrush(QPalette::Inactive, QPalette::Button, brush9);
        palette15.setBrush(QPalette::Inactive, QPalette::Light, brush10);
        palette15.setBrush(QPalette::Inactive, QPalette::Midlight, brush11);
        palette15.setBrush(QPalette::Inactive, QPalette::Dark, brush12);
        palette15.setBrush(QPalette::Inactive, QPalette::Mid, brush13);
        palette15.setBrush(QPalette::Inactive, QPalette::Text, brush6);
        palette15.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette15.setBrush(QPalette::Inactive, QPalette::ButtonText, brush6);
        palette15.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette15.setBrush(QPalette::Inactive, QPalette::Window, brush9);
        palette15.setBrush(QPalette::Inactive, QPalette::Shadow, brush6);
        palette15.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush14);
        palette15.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette15.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush6);
        palette15.setBrush(QPalette::Disabled, QPalette::WindowText, brush12);
        palette15.setBrush(QPalette::Disabled, QPalette::Button, brush9);
        palette15.setBrush(QPalette::Disabled, QPalette::Light, brush10);
        palette15.setBrush(QPalette::Disabled, QPalette::Midlight, brush11);
        palette15.setBrush(QPalette::Disabled, QPalette::Dark, brush12);
        palette15.setBrush(QPalette::Disabled, QPalette::Mid, brush13);
        palette15.setBrush(QPalette::Disabled, QPalette::Text, brush12);
        palette15.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette15.setBrush(QPalette::Disabled, QPalette::ButtonText, brush12);
        palette15.setBrush(QPalette::Disabled, QPalette::Base, brush9);
        palette15.setBrush(QPalette::Disabled, QPalette::Window, brush9);
        palette15.setBrush(QPalette::Disabled, QPalette::Shadow, brush6);
        palette15.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush9);
        palette15.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette15.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush6);
        pbtn_go->setPalette(palette15);
        pbtn_go->setFont(font);
        pbtn_go->setFocusPolicy(Qt::NoFocus);
        pbtn_go->setStyleSheet(QString::fromUtf8("border-image: url(:/btn/qrc/PICS/Pbtn.png);"));
        label_logo = new QLabel(frame_4);
        label_logo->setObjectName(QString::fromUtf8("label_logo"));
        label_logo->setGeometry(QRect(160, 0, 481, 81));
        QPalette palette16;
        palette16.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette16.setBrush(QPalette::Active, QPalette::Button, brush6);
        palette16.setBrush(QPalette::Active, QPalette::Light, brush6);
        palette16.setBrush(QPalette::Active, QPalette::Midlight, brush6);
        palette16.setBrush(QPalette::Active, QPalette::Dark, brush6);
        palette16.setBrush(QPalette::Active, QPalette::Mid, brush6);
        palette16.setBrush(QPalette::Active, QPalette::Text, brush);
        palette16.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette16.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette16.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette16.setBrush(QPalette::Active, QPalette::Window, brush6);
        palette16.setBrush(QPalette::Active, QPalette::Shadow, brush6);
        palette16.setBrush(QPalette::Active, QPalette::AlternateBase, brush6);
        palette16.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette16.setBrush(QPalette::Active, QPalette::ToolTipText, brush6);
        palette16.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette16.setBrush(QPalette::Inactive, QPalette::Button, brush6);
        palette16.setBrush(QPalette::Inactive, QPalette::Light, brush6);
        palette16.setBrush(QPalette::Inactive, QPalette::Midlight, brush6);
        palette16.setBrush(QPalette::Inactive, QPalette::Dark, brush6);
        palette16.setBrush(QPalette::Inactive, QPalette::Mid, brush6);
        palette16.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette16.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette16.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette16.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette16.setBrush(QPalette::Inactive, QPalette::Window, brush6);
        palette16.setBrush(QPalette::Inactive, QPalette::Shadow, brush6);
        palette16.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush6);
        palette16.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette16.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush6);
        palette16.setBrush(QPalette::Disabled, QPalette::WindowText, brush6);
        palette16.setBrush(QPalette::Disabled, QPalette::Button, brush6);
        palette16.setBrush(QPalette::Disabled, QPalette::Light, brush6);
        palette16.setBrush(QPalette::Disabled, QPalette::Midlight, brush6);
        palette16.setBrush(QPalette::Disabled, QPalette::Dark, brush6);
        palette16.setBrush(QPalette::Disabled, QPalette::Mid, brush6);
        palette16.setBrush(QPalette::Disabled, QPalette::Text, brush6);
        palette16.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette16.setBrush(QPalette::Disabled, QPalette::ButtonText, brush6);
        palette16.setBrush(QPalette::Disabled, QPalette::Base, brush6);
        palette16.setBrush(QPalette::Disabled, QPalette::Window, brush6);
        palette16.setBrush(QPalette::Disabled, QPalette::Shadow, brush6);
        palette16.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush6);
        palette16.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette16.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush6);
        label_logo->setPalette(palette16);
        QFont font2;
        font2.setPointSize(40);
        font2.setBold(true);
        font2.setWeight(75);
        label_logo->setFont(font2);
        label_logo->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/mainlab_phonenum.png);"));
        label_logo->setTextFormat(Qt::AutoText);
        label_logo->setAlignment(Qt::AlignCenter);
        label_stubnum = new QLabel(frame_4);
        label_stubnum->setObjectName(QString::fromUtf8("label_stubnum"));
        label_stubnum->setGeometry(QRect(33, 450, 171, 31));
        QPalette palette17;
        palette17.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette17.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette17.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette17.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        palette17.setBrush(QPalette::Active, QPalette::Dark, brush4);
        palette17.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette17.setBrush(QPalette::Active, QPalette::Text, brush6);
        palette17.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette17.setBrush(QPalette::Active, QPalette::ButtonText, brush6);
        palette17.setBrush(QPalette::Active, QPalette::Base, brush);
        palette17.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette17.setBrush(QPalette::Active, QPalette::Shadow, brush6);
        palette17.setBrush(QPalette::Active, QPalette::AlternateBase, brush7);
        palette17.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette17.setBrush(QPalette::Active, QPalette::ToolTipText, brush6);
        palette17.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette17.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette17.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette17.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette17.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette17.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette17.setBrush(QPalette::Inactive, QPalette::Text, brush6);
        palette17.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette17.setBrush(QPalette::Inactive, QPalette::ButtonText, brush6);
        palette17.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette17.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette17.setBrush(QPalette::Inactive, QPalette::Shadow, brush6);
        palette17.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush7);
        palette17.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette17.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush6);
        palette17.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette17.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette17.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette17.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette17.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette17.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette17.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette17.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette17.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette17.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette17.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette17.setBrush(QPalette::Disabled, QPalette::Shadow, brush6);
        palette17.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette17.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette17.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush6);
        label_stubnum->setPalette(palette17);
        label_stubnum->setFont(font);
        label_stubnum->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/mainlab_phonenum.png);"));
        label_stubnum->setTextFormat(Qt::AutoText);
        lbl_time_chose = new QLineEdit(frame_4);
        lbl_time_chose->setObjectName(QString::fromUtf8("lbl_time_chose"));
        lbl_time_chose->setGeometry(QRect(315, 150, 91, 51));
        QFont font3;
        font3.setPointSize(30);
        lbl_time_chose->setFont(font3);
        lbl_time_chose->setFocusPolicy(Qt::StrongFocus);
        lbl_time_chose->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/frame_white.png);"));
        lbl_time_chose->setFrame(true);
        lbl_time_chose->setEchoMode(QLineEdit::Normal);
        lbl_time_chose->setAlignment(Qt::AlignCenter);
        label_2 = new QLabel(frame_4);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(430, 146, 81, 51));
        label_2->setFont(font3);
        label_2->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/frame_white.png);"));
        pbtn_180min = new QPushButton(frame_4);
        pbtn_180min->setObjectName(QString::fromUtf8("pbtn_180min"));
        pbtn_180min->setGeometry(QRect(420, 400, 91, 51));
        QPalette palette18;
        palette18.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette18.setBrush(QPalette::Active, QPalette::Button, brush6);
        palette18.setBrush(QPalette::Active, QPalette::Light, brush6);
        palette18.setBrush(QPalette::Active, QPalette::Midlight, brush6);
        palette18.setBrush(QPalette::Active, QPalette::Dark, brush6);
        palette18.setBrush(QPalette::Active, QPalette::Mid, brush6);
        palette18.setBrush(QPalette::Active, QPalette::Text, brush);
        palette18.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette18.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette18.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette18.setBrush(QPalette::Active, QPalette::Window, brush6);
        palette18.setBrush(QPalette::Active, QPalette::Shadow, brush6);
        palette18.setBrush(QPalette::Active, QPalette::AlternateBase, brush6);
        palette18.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette18.setBrush(QPalette::Active, QPalette::ToolTipText, brush6);
        palette18.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette18.setBrush(QPalette::Inactive, QPalette::Button, brush6);
        palette18.setBrush(QPalette::Inactive, QPalette::Light, brush6);
        palette18.setBrush(QPalette::Inactive, QPalette::Midlight, brush6);
        palette18.setBrush(QPalette::Inactive, QPalette::Dark, brush6);
        palette18.setBrush(QPalette::Inactive, QPalette::Mid, brush6);
        palette18.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette18.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette18.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette18.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette18.setBrush(QPalette::Inactive, QPalette::Window, brush6);
        palette18.setBrush(QPalette::Inactive, QPalette::Shadow, brush6);
        palette18.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush6);
        palette18.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette18.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush6);
        palette18.setBrush(QPalette::Disabled, QPalette::WindowText, brush6);
        palette18.setBrush(QPalette::Disabled, QPalette::Button, brush6);
        palette18.setBrush(QPalette::Disabled, QPalette::Light, brush6);
        palette18.setBrush(QPalette::Disabled, QPalette::Midlight, brush6);
        palette18.setBrush(QPalette::Disabled, QPalette::Dark, brush6);
        palette18.setBrush(QPalette::Disabled, QPalette::Mid, brush6);
        palette18.setBrush(QPalette::Disabled, QPalette::Text, brush6);
        palette18.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette18.setBrush(QPalette::Disabled, QPalette::ButtonText, brush6);
        palette18.setBrush(QPalette::Disabled, QPalette::Base, brush6);
        palette18.setBrush(QPalette::Disabled, QPalette::Window, brush6);
        palette18.setBrush(QPalette::Disabled, QPalette::Shadow, brush6);
        palette18.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush6);
        palette18.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette18.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush6);
        pbtn_180min->setPalette(palette18);
        QFont font4;
        font4.setPointSize(18);
        pbtn_180min->setFont(font4);
        pbtn_180min->setFocusPolicy(Qt::NoFocus);
        pbtn_180min->setStyleSheet(QString::fromUtf8("border-image: url(:/btn/qrc/PICS/button.png);"));
        pbtn_60min = new QPushButton(frame_4);
        pbtn_60min->setObjectName(QString::fromUtf8("pbtn_60min"));
        pbtn_60min->setGeometry(QRect(290, 400, 91, 51));
        QPalette palette19;
        palette19.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette19.setBrush(QPalette::Active, QPalette::Button, brush6);
        palette19.setBrush(QPalette::Active, QPalette::Light, brush6);
        palette19.setBrush(QPalette::Active, QPalette::Midlight, brush6);
        palette19.setBrush(QPalette::Active, QPalette::Dark, brush6);
        palette19.setBrush(QPalette::Active, QPalette::Mid, brush6);
        palette19.setBrush(QPalette::Active, QPalette::Text, brush);
        palette19.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette19.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette19.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette19.setBrush(QPalette::Active, QPalette::Window, brush6);
        palette19.setBrush(QPalette::Active, QPalette::Shadow, brush6);
        palette19.setBrush(QPalette::Active, QPalette::AlternateBase, brush6);
        palette19.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette19.setBrush(QPalette::Active, QPalette::ToolTipText, brush6);
        palette19.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette19.setBrush(QPalette::Inactive, QPalette::Button, brush6);
        palette19.setBrush(QPalette::Inactive, QPalette::Light, brush6);
        palette19.setBrush(QPalette::Inactive, QPalette::Midlight, brush6);
        palette19.setBrush(QPalette::Inactive, QPalette::Dark, brush6);
        palette19.setBrush(QPalette::Inactive, QPalette::Mid, brush6);
        palette19.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette19.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette19.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette19.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette19.setBrush(QPalette::Inactive, QPalette::Window, brush6);
        palette19.setBrush(QPalette::Inactive, QPalette::Shadow, brush6);
        palette19.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush6);
        palette19.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette19.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush6);
        palette19.setBrush(QPalette::Disabled, QPalette::WindowText, brush6);
        palette19.setBrush(QPalette::Disabled, QPalette::Button, brush6);
        palette19.setBrush(QPalette::Disabled, QPalette::Light, brush6);
        palette19.setBrush(QPalette::Disabled, QPalette::Midlight, brush6);
        palette19.setBrush(QPalette::Disabled, QPalette::Dark, brush6);
        palette19.setBrush(QPalette::Disabled, QPalette::Mid, brush6);
        palette19.setBrush(QPalette::Disabled, QPalette::Text, brush6);
        palette19.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette19.setBrush(QPalette::Disabled, QPalette::ButtonText, brush6);
        palette19.setBrush(QPalette::Disabled, QPalette::Base, brush6);
        palette19.setBrush(QPalette::Disabled, QPalette::Window, brush6);
        palette19.setBrush(QPalette::Disabled, QPalette::Shadow, brush6);
        palette19.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush6);
        palette19.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette19.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush6);
        pbtn_60min->setPalette(palette19);
        pbtn_60min->setFont(font4);
        pbtn_60min->setFocusPolicy(Qt::NoFocus);
        pbtn_60min->setStyleSheet(QString::fromUtf8("border-image: url(:/btn/qrc/PICS/button.png);"));
        pbtn_30min = new QPushButton(frame_4);
        pbtn_30min->setObjectName(QString::fromUtf8("pbtn_30min"));
        pbtn_30min->setGeometry(QRect(160, 400, 91, 51));
        QPalette palette20;
        palette20.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette20.setBrush(QPalette::Active, QPalette::Button, brush6);
        palette20.setBrush(QPalette::Active, QPalette::Light, brush6);
        palette20.setBrush(QPalette::Active, QPalette::Midlight, brush6);
        palette20.setBrush(QPalette::Active, QPalette::Dark, brush6);
        palette20.setBrush(QPalette::Active, QPalette::Mid, brush6);
        palette20.setBrush(QPalette::Active, QPalette::Text, brush);
        palette20.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette20.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette20.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette20.setBrush(QPalette::Active, QPalette::Window, brush6);
        palette20.setBrush(QPalette::Active, QPalette::Shadow, brush6);
        palette20.setBrush(QPalette::Active, QPalette::AlternateBase, brush6);
        palette20.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette20.setBrush(QPalette::Active, QPalette::ToolTipText, brush6);
        palette20.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette20.setBrush(QPalette::Inactive, QPalette::Button, brush6);
        palette20.setBrush(QPalette::Inactive, QPalette::Light, brush6);
        palette20.setBrush(QPalette::Inactive, QPalette::Midlight, brush6);
        palette20.setBrush(QPalette::Inactive, QPalette::Dark, brush6);
        palette20.setBrush(QPalette::Inactive, QPalette::Mid, brush6);
        palette20.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette20.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette20.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette20.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette20.setBrush(QPalette::Inactive, QPalette::Window, brush6);
        palette20.setBrush(QPalette::Inactive, QPalette::Shadow, brush6);
        palette20.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush6);
        palette20.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette20.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush6);
        palette20.setBrush(QPalette::Disabled, QPalette::WindowText, brush6);
        palette20.setBrush(QPalette::Disabled, QPalette::Button, brush6);
        palette20.setBrush(QPalette::Disabled, QPalette::Light, brush6);
        palette20.setBrush(QPalette::Disabled, QPalette::Midlight, brush6);
        palette20.setBrush(QPalette::Disabled, QPalette::Dark, brush6);
        palette20.setBrush(QPalette::Disabled, QPalette::Mid, brush6);
        palette20.setBrush(QPalette::Disabled, QPalette::Text, brush6);
        palette20.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette20.setBrush(QPalette::Disabled, QPalette::ButtonText, brush6);
        palette20.setBrush(QPalette::Disabled, QPalette::Base, brush6);
        palette20.setBrush(QPalette::Disabled, QPalette::Window, brush6);
        palette20.setBrush(QPalette::Disabled, QPalette::Shadow, brush6);
        palette20.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush6);
        palette20.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette20.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush6);
        pbtn_30min->setPalette(palette20);
        pbtn_30min->setFont(font4);
        pbtn_30min->setFocusPolicy(Qt::NoFocus);
        pbtn_30min->setStyleSheet(QString::fromUtf8("border-image: url(:/btn/qrc/PICS/button.png);"));
        pbtn_120min = new QPushButton(frame_4);
        pbtn_120min->setObjectName(QString::fromUtf8("pbtn_120min"));
        pbtn_120min->setGeometry(QRect(550, 400, 91, 51));
        QPalette palette21;
        palette21.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette21.setBrush(QPalette::Active, QPalette::Button, brush6);
        palette21.setBrush(QPalette::Active, QPalette::Light, brush6);
        palette21.setBrush(QPalette::Active, QPalette::Midlight, brush6);
        palette21.setBrush(QPalette::Active, QPalette::Dark, brush6);
        palette21.setBrush(QPalette::Active, QPalette::Mid, brush6);
        palette21.setBrush(QPalette::Active, QPalette::Text, brush);
        palette21.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette21.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette21.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette21.setBrush(QPalette::Active, QPalette::Window, brush6);
        palette21.setBrush(QPalette::Active, QPalette::Shadow, brush6);
        palette21.setBrush(QPalette::Active, QPalette::AlternateBase, brush6);
        palette21.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette21.setBrush(QPalette::Active, QPalette::ToolTipText, brush6);
        palette21.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette21.setBrush(QPalette::Inactive, QPalette::Button, brush6);
        palette21.setBrush(QPalette::Inactive, QPalette::Light, brush6);
        palette21.setBrush(QPalette::Inactive, QPalette::Midlight, brush6);
        palette21.setBrush(QPalette::Inactive, QPalette::Dark, brush6);
        palette21.setBrush(QPalette::Inactive, QPalette::Mid, brush6);
        palette21.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette21.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette21.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette21.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette21.setBrush(QPalette::Inactive, QPalette::Window, brush6);
        palette21.setBrush(QPalette::Inactive, QPalette::Shadow, brush6);
        palette21.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush6);
        palette21.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette21.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush6);
        palette21.setBrush(QPalette::Disabled, QPalette::WindowText, brush6);
        palette21.setBrush(QPalette::Disabled, QPalette::Button, brush6);
        palette21.setBrush(QPalette::Disabled, QPalette::Light, brush6);
        palette21.setBrush(QPalette::Disabled, QPalette::Midlight, brush6);
        palette21.setBrush(QPalette::Disabled, QPalette::Dark, brush6);
        palette21.setBrush(QPalette::Disabled, QPalette::Mid, brush6);
        palette21.setBrush(QPalette::Disabled, QPalette::Text, brush6);
        palette21.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette21.setBrush(QPalette::Disabled, QPalette::ButtonText, brush6);
        palette21.setBrush(QPalette::Disabled, QPalette::Base, brush6);
        palette21.setBrush(QPalette::Disabled, QPalette::Window, brush6);
        palette21.setBrush(QPalette::Disabled, QPalette::Shadow, brush6);
        palette21.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush6);
        palette21.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette21.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush6);
        pbtn_120min->setPalette(palette21);
        pbtn_120min->setFont(font4);
        pbtn_120min->setFocusPolicy(Qt::NoFocus);
        pbtn_120min->setStyleSheet(QString::fromUtf8("border-image: url(:/btn/qrc/PICS/button.png);"));
        label_code = new QLabel(frame_4);
        label_code->setObjectName(QString::fromUtf8("label_code"));
        label_code->setGeometry(QRect(193, 452, 251, 31));
        QPalette palette22;
        palette22.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette22.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette22.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette22.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        palette22.setBrush(QPalette::Active, QPalette::Dark, brush4);
        palette22.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette22.setBrush(QPalette::Active, QPalette::Text, brush6);
        palette22.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette22.setBrush(QPalette::Active, QPalette::ButtonText, brush6);
        palette22.setBrush(QPalette::Active, QPalette::Base, brush);
        palette22.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette22.setBrush(QPalette::Active, QPalette::Shadow, brush6);
        palette22.setBrush(QPalette::Active, QPalette::AlternateBase, brush7);
        palette22.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette22.setBrush(QPalette::Active, QPalette::ToolTipText, brush6);
        palette22.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette22.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette22.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette22.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette22.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette22.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette22.setBrush(QPalette::Inactive, QPalette::Text, brush6);
        palette22.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette22.setBrush(QPalette::Inactive, QPalette::ButtonText, brush6);
        palette22.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette22.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette22.setBrush(QPalette::Inactive, QPalette::Shadow, brush6);
        palette22.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush7);
        palette22.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette22.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush6);
        palette22.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette22.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette22.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette22.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette22.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette22.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette22.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette22.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette22.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette22.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette22.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette22.setBrush(QPalette::Disabled, QPalette::Shadow, brush6);
        palette22.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette22.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette22.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush6);
        label_code->setPalette(palette22);
        label_code->setFont(font);
        label_code->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/mainlab_phonenum.png);"));
        label_code->setTextFormat(Qt::AutoText);

        retranslateUi(p23_chargebymoney);

        QMetaObject::connectSlotsByName(p23_chargebymoney);
    } // setupUi

    void retranslateUi(QDialog *p23_chargebymoney)
    {
        p23_chargebymoney->setWindowTitle(QApplication::translate("p23_chargebymoney", "Dialog", 0, QApplication::UnicodeUTF8));
        label_phone->setText(QString());
        label_phone_2->setText(QString());
        lbl_speaker->setText(QString());
        pbtn_num0->setText(QApplication::translate("p23_chargebymoney", "0", 0, QApplication::UnicodeUTF8));
        pbtn_num1->setText(QApplication::translate("p23_chargebymoney", "1", 0, QApplication::UnicodeUTF8));
        pbtn_num2->setText(QApplication::translate("p23_chargebymoney", "2", 0, QApplication::UnicodeUTF8));
        pbtn_num5->setText(QApplication::translate("p23_chargebymoney", "5", 0, QApplication::UnicodeUTF8));
        pbtn_num3->setText(QApplication::translate("p23_chargebymoney", "3", 0, QApplication::UnicodeUTF8));
        pbtn_num4->setText(QApplication::translate("p23_chargebymoney", "4", 0, QApplication::UnicodeUTF8));
        pbtn_num6->setText(QApplication::translate("p23_chargebymoney", "6", 0, QApplication::UnicodeUTF8));
        pbtn_back->setText(QApplication::translate("p23_chargebymoney", "C", 0, QApplication::UnicodeUTF8));
        pbtn_num7->setText(QApplication::translate("p23_chargebymoney", "7", 0, QApplication::UnicodeUTF8));
        pbtn_dot->setText(QApplication::translate("p23_chargebymoney", "*", 0, QApplication::UnicodeUTF8));
        pbtn_num8->setText(QApplication::translate("p23_chargebymoney", "8", 0, QApplication::UnicodeUTF8));
        pbtn_num9->setText(QApplication::translate("p23_chargebymoney", "9", 0, QApplication::UnicodeUTF8));
        pbtn_ok->setText(QString());
        pbtn_go->setText(QString());
        label_logo->setText(QString());
        label_stubnum->setText(QString());
        lbl_time_chose->setText(QString());
        label_2->setText(QApplication::translate("p23_chargebymoney", "\302\245", 0, QApplication::UnicodeUTF8));
        pbtn_180min->setText(QApplication::translate("p23_chargebymoney", "15\302\245", 0, QApplication::UnicodeUTF8));
        pbtn_60min->setText(QApplication::translate("p23_chargebymoney", "10\302\245", 0, QApplication::UnicodeUTF8));
        pbtn_30min->setText(QApplication::translate("p23_chargebymoney", "5\302\245", 0, QApplication::UnicodeUTF8));
        pbtn_120min->setText(QApplication::translate("p23_chargebymoney", "20\302\245", 0, QApplication::UnicodeUTF8));
        label_code->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class p23_chargebymoney: public Ui_p23_chargebymoney {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_P23_CHARGEBYMONEY_H
