/********************************************************************************
** Form generated from reading UI file 'p11_charging_dialog.ui'
**
** Created: Wed Dec 31 14:57:40 2014
**      by: Qt User Interface Compiler version 4.8.4
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_P11_CHARGING_DIALOG_H
#define UI_P11_CHARGING_DIALOG_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QDialog>
#include <QtGui/QFrame>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>

QT_BEGIN_NAMESPACE

class Ui_p11_charging_dialog
{
public:
    QFrame *frame_4;
    QFrame *frame_5;
    QFrame *frame_3;
    QLabel *lbl_output_voltage;
    QLabel *lbl_;
    QLabel *label_volt;
    QFrame *frame_9;
    QLabel *lbl_caculate_energy;
    QLabel *lbl_caculate_energy_3;
    QLabel *label_energy;
    QFrame *frame_11;
    QLabel *label_time;
    QLabel *lbl_time_hour_3;
    QLabel *lbl_time_hour;
    QLabel *lbl_time_hour_2;
    QLabel *lbl_time_min;
    QFrame *frame_12;
    QLabel *label_state;
    QLabel *lbl_chg_cur_stat;
    QFrame *frame_6;
    QLabel *lbl_ouput_current;
    QLabel *label_card_sn_16;
    QLabel *label_current;
    QLabel *label_equipment;
    QFrame *frame_13;
    QLabel *label_moudletemp;
    QLabel *lbl_time_hour_6;
    QLabel *lbl_h_moudle;
    QFrame *frame_7;
    QLabel *lbl_h_volt;
    QLabel *label_card_sn_17;
    QLabel *label_highvlot;
    QFrame *frame_10;
    QLabel *lbl_current_soc;
    QLabel *lbl_caculate_energy_4;
    QLabel *label_soc;
    QFrame *frame_14;
    QLabel *label_hightemp;
    QLabel *lbl_time_hour_7;
    QLabel *lbl_h_temp;
    QFrame *frame_15;
    QLabel *label_lowvolt;
    QLabel *label_card_sn_18;
    QLabel *lbl_l_volt;
    QFrame *frame_16;
    QLabel *label_state_2;
    QLabel *label_14;
    QFrame *frame_8;
    QLabel *lbl_left_time;
    QLabel *lbl_1;
    QLabel *label_lefttime;
    QLabel *label_phone;
    QLabel *label_phone_2;
    QLabel *label_logo;
    QLabel *label_title_2;
    QLabel *label_stubnum;
    QLabel *label_code;

    void setupUi(QDialog *p11_charging_dialog)
    {
        if (p11_charging_dialog->objectName().isEmpty())
            p11_charging_dialog->setObjectName(QString::fromUtf8("p11_charging_dialog"));
        p11_charging_dialog->resize(800, 480);
        p11_charging_dialog->setStyleSheet(QString::fromUtf8(""));
        frame_4 = new QFrame(p11_charging_dialog);
        frame_4->setObjectName(QString::fromUtf8("frame_4"));
        frame_4->setGeometry(QRect(0, 0, 800, 480));
        frame_4->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/PICS/backgroud_1.png);"));
        frame_4->setFrameShape(QFrame::StyledPanel);
        frame_4->setFrameShadow(QFrame::Raised);
        frame_5 = new QFrame(frame_4);
        frame_5->setObjectName(QString::fromUtf8("frame_5"));
        frame_5->setGeometry(QRect(26, 140, 751, 321));
        QFont font;
        font.setPointSize(20);
        frame_5->setFont(font);
        frame_5->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/back.png);"));
        frame_5->setFrameShape(QFrame::NoFrame);
        frame_5->setFrameShadow(QFrame::Raised);
        frame_3 = new QFrame(frame_5);
        frame_3->setObjectName(QString::fromUtf8("frame_3"));
        frame_3->setGeometry(QRect(430, 51, 301, 51));
        QSizePolicy sizePolicy(QSizePolicy::Ignored, QSizePolicy::Ignored);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(frame_3->sizePolicy().hasHeightForWidth());
        frame_3->setSizePolicy(sizePolicy);
        frame_3->setMinimumSize(QSize(13, 0));
        QFont font1;
        font1.setPointSize(24);
        font1.setBold(true);
        font1.setWeight(75);
        font1.setKerning(true);
        frame_3->setFont(font1);
        frame_3->setAutoFillBackground(false);
        frame_3->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/back.png);\n"
" "));
        frame_3->setFrameShape(QFrame::Box);
        frame_3->setFrameShadow(QFrame::Sunken);
        lbl_output_voltage = new QLabel(frame_3);
        lbl_output_voltage->setObjectName(QString::fromUtf8("lbl_output_voltage"));
        lbl_output_voltage->setGeometry(QRect(169, 12, 81, 31));
        QFont font2;
        font2.setFamily(QString::fromUtf8("Courier 10 Pitch"));
        font2.setPointSize(20);
        font2.setBold(false);
        font2.setItalic(false);
        font2.setWeight(50);
        font2.setKerning(true);
        lbl_output_voltage->setFont(font2);
        lbl_output_voltage->setFrameShape(QFrame::NoFrame);
        lbl_ = new QLabel(frame_3);
        lbl_->setObjectName(QString::fromUtf8("lbl_"));
        lbl_->setGeometry(QRect(260, 12, 31, 31));
        lbl_->setFont(font2);
        label_volt = new QLabel(frame_3);
        label_volt->setObjectName(QString::fromUtf8("label_volt"));
        label_volt->setGeometry(QRect(10, 15, 111, 21));
        QFont font3;
        font3.setPointSize(20);
        font3.setItalic(false);
        label_volt->setFont(font3);
        frame_9 = new QFrame(frame_5);
        frame_9->setObjectName(QString::fromUtf8("frame_9"));
        frame_9->setGeometry(QRect(430, 1, 301, 51));
        sizePolicy.setHeightForWidth(frame_9->sizePolicy().hasHeightForWidth());
        frame_9->setSizePolicy(sizePolicy);
        frame_9->setMinimumSize(QSize(13, 0));
        frame_9->setFont(font1);
        frame_9->setAutoFillBackground(false);
        frame_9->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/back.png);\n"
" "));
        frame_9->setFrameShape(QFrame::Box);
        frame_9->setFrameShadow(QFrame::Sunken);
        lbl_caculate_energy = new QLabel(frame_9);
        lbl_caculate_energy->setObjectName(QString::fromUtf8("lbl_caculate_energy"));
        lbl_caculate_energy->setGeometry(QRect(169, 12, 81, 31));
        lbl_caculate_energy->setFont(font2);
        lbl_caculate_energy->setFrameShape(QFrame::NoFrame);
        lbl_caculate_energy_3 = new QLabel(frame_9);
        lbl_caculate_energy_3->setObjectName(QString::fromUtf8("lbl_caculate_energy_3"));
        lbl_caculate_energy_3->setGeometry(QRect(260, 10, 51, 31));
        lbl_caculate_energy_3->setFont(font2);
        label_energy = new QLabel(frame_9);
        label_energy->setObjectName(QString::fromUtf8("label_energy"));
        label_energy->setGeometry(QRect(10, 15, 121, 21));
        label_energy->setFont(font3);
        frame_11 = new QFrame(frame_5);
        frame_11->setObjectName(QString::fromUtf8("frame_11"));
        frame_11->setGeometry(QRect(20, 50, 301, 51));
        sizePolicy.setHeightForWidth(frame_11->sizePolicy().hasHeightForWidth());
        frame_11->setSizePolicy(sizePolicy);
        frame_11->setMinimumSize(QSize(13, 0));
        frame_11->setFont(font1);
        frame_11->setAutoFillBackground(false);
        frame_11->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/back.png);\n"
" "));
        frame_11->setFrameShape(QFrame::Box);
        frame_11->setFrameShadow(QFrame::Sunken);
        label_time = new QLabel(frame_11);
        label_time->setObjectName(QString::fromUtf8("label_time"));
        label_time->setGeometry(QRect(10, 15, 141, 21));
        label_time->setFont(font3);
        lbl_time_hour_3 = new QLabel(frame_11);
        lbl_time_hour_3->setObjectName(QString::fromUtf8("lbl_time_hour_3"));
        lbl_time_hour_3->setGeometry(QRect(255, 12, 51, 31));
        lbl_time_hour_3->setFont(font2);
        lbl_time_hour = new QLabel(frame_11);
        lbl_time_hour->setObjectName(QString::fromUtf8("lbl_time_hour"));
        lbl_time_hour->setGeometry(QRect(170, 12, 31, 31));
        lbl_time_hour->setFont(font2);
        lbl_time_hour->setFrameShape(QFrame::NoFrame);
        lbl_time_hour->setAlignment(Qt::AlignCenter);
        lbl_time_hour_2 = new QLabel(frame_11);
        lbl_time_hour_2->setObjectName(QString::fromUtf8("lbl_time_hour_2"));
        lbl_time_hour_2->setGeometry(QRect(200, 12, 31, 31));
        lbl_time_hour_2->setFont(font2);
        lbl_time_min = new QLabel(frame_11);
        lbl_time_min->setObjectName(QString::fromUtf8("lbl_time_min"));
        lbl_time_min->setGeometry(QRect(224, 12, 31, 31));
        lbl_time_min->setFont(font2);
        lbl_time_min->setFrameShape(QFrame::NoFrame);
        lbl_time_min->setAlignment(Qt::AlignCenter);
        frame_12 = new QFrame(frame_5);
        frame_12->setObjectName(QString::fromUtf8("frame_12"));
        frame_12->setGeometry(QRect(430, 149, 301, 51));
        sizePolicy.setHeightForWidth(frame_12->sizePolicy().hasHeightForWidth());
        frame_12->setSizePolicy(sizePolicy);
        frame_12->setMinimumSize(QSize(13, 0));
        frame_12->setFont(font1);
        frame_12->setAutoFillBackground(false);
        frame_12->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/back.png);\n"
" "));
        frame_12->setFrameShape(QFrame::Box);
        frame_12->setFrameShadow(QFrame::Sunken);
        label_state = new QLabel(frame_12);
        label_state->setObjectName(QString::fromUtf8("label_state"));
        label_state->setGeometry(QRect(10, 15, 91, 21));
        label_state->setFont(font3);
        lbl_chg_cur_stat = new QLabel(frame_12);
        lbl_chg_cur_stat->setObjectName(QString::fromUtf8("lbl_chg_cur_stat"));
        lbl_chg_cur_stat->setGeometry(QRect(170, 15, 121, 21));
        QFont font4;
        font4.setPointSize(18);
        font4.setItalic(false);
        lbl_chg_cur_stat->setFont(font4);
        lbl_chg_cur_stat->setFrameShape(QFrame::NoFrame);
        lbl_chg_cur_stat->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        frame_6 = new QFrame(frame_5);
        frame_6->setObjectName(QString::fromUtf8("frame_6"));
        frame_6->setGeometry(QRect(430, 100, 301, 51));
        sizePolicy.setHeightForWidth(frame_6->sizePolicy().hasHeightForWidth());
        frame_6->setSizePolicy(sizePolicy);
        frame_6->setMinimumSize(QSize(13, 0));
        frame_6->setFont(font1);
        frame_6->setAutoFillBackground(false);
        frame_6->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/back.png);\n"
" "));
        frame_6->setFrameShape(QFrame::Box);
        frame_6->setFrameShadow(QFrame::Sunken);
        lbl_ouput_current = new QLabel(frame_6);
        lbl_ouput_current->setObjectName(QString::fromUtf8("lbl_ouput_current"));
        lbl_ouput_current->setGeometry(QRect(169, 12, 81, 31));
        lbl_ouput_current->setFont(font2);
        lbl_ouput_current->setFrameShape(QFrame::NoFrame);
        label_card_sn_16 = new QLabel(frame_6);
        label_card_sn_16->setObjectName(QString::fromUtf8("label_card_sn_16"));
        label_card_sn_16->setGeometry(QRect(260, 12, 31, 31));
        label_card_sn_16->setFont(font2);
        label_current = new QLabel(frame_6);
        label_current->setObjectName(QString::fromUtf8("label_current"));
        label_current->setGeometry(QRect(10, 15, 131, 21));
        label_current->setFont(font3);
        label_equipment = new QLabel(frame_5);
        label_equipment->setObjectName(QString::fromUtf8("label_equipment"));
        label_equipment->setGeometry(QRect(20, 230, 141, 21));
        label_equipment->setFont(font3);
        frame_13 = new QFrame(frame_5);
        frame_13->setObjectName(QString::fromUtf8("frame_13"));
        frame_13->setGeometry(QRect(430, 247, 301, 51));
        sizePolicy.setHeightForWidth(frame_13->sizePolicy().hasHeightForWidth());
        frame_13->setSizePolicy(sizePolicy);
        frame_13->setMinimumSize(QSize(13, 0));
        frame_13->setFont(font1);
        frame_13->setAutoFillBackground(false);
        frame_13->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/back.png);\n"
" "));
        frame_13->setFrameShape(QFrame::Box);
        frame_13->setFrameShadow(QFrame::Sunken);
        label_moudletemp = new QLabel(frame_13);
        label_moudletemp->setObjectName(QString::fromUtf8("label_moudletemp"));
        label_moudletemp->setGeometry(QRect(10, 15, 151, 21));
        label_moudletemp->setFont(font3);
        lbl_time_hour_6 = new QLabel(frame_13);
        lbl_time_hour_6->setObjectName(QString::fromUtf8("lbl_time_hour_6"));
        lbl_time_hour_6->setGeometry(QRect(260, 12, 31, 31));
        lbl_time_hour_6->setFont(font2);
        lbl_h_moudle = new QLabel(frame_13);
        lbl_h_moudle->setObjectName(QString::fromUtf8("lbl_h_moudle"));
        lbl_h_moudle->setGeometry(QRect(169, 12, 81, 31));
        lbl_h_moudle->setFont(font2);
        lbl_h_moudle->setFrameShape(QFrame::NoFrame);
        frame_7 = new QFrame(frame_5);
        frame_7->setObjectName(QString::fromUtf8("frame_7"));
        frame_7->setGeometry(QRect(20, 149, 301, 51));
        sizePolicy.setHeightForWidth(frame_7->sizePolicy().hasHeightForWidth());
        frame_7->setSizePolicy(sizePolicy);
        frame_7->setMinimumSize(QSize(13, 0));
        frame_7->setFont(font1);
        frame_7->setAutoFillBackground(false);
        frame_7->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/back.png);\n"
" "));
        frame_7->setFrameShape(QFrame::Box);
        frame_7->setFrameShadow(QFrame::Sunken);
        lbl_h_volt = new QLabel(frame_7);
        lbl_h_volt->setObjectName(QString::fromUtf8("lbl_h_volt"));
        lbl_h_volt->setGeometry(QRect(174, 12, 81, 31));
        lbl_h_volt->setFont(font2);
        lbl_h_volt->setFrameShape(QFrame::NoFrame);
        label_card_sn_17 = new QLabel(frame_7);
        label_card_sn_17->setObjectName(QString::fromUtf8("label_card_sn_17"));
        label_card_sn_17->setGeometry(QRect(255, 12, 31, 31));
        label_card_sn_17->setFont(font2);
        label_highvlot = new QLabel(frame_7);
        label_highvlot->setObjectName(QString::fromUtf8("label_highvlot"));
        label_highvlot->setGeometry(QRect(10, 15, 141, 21));
        label_highvlot->setFont(font3);
        frame_10 = new QFrame(frame_5);
        frame_10->setObjectName(QString::fromUtf8("frame_10"));
        frame_10->setGeometry(QRect(20, 1, 301, 51));
        sizePolicy.setHeightForWidth(frame_10->sizePolicy().hasHeightForWidth());
        frame_10->setSizePolicy(sizePolicy);
        frame_10->setMinimumSize(QSize(13, 0));
        frame_10->setFont(font1);
        frame_10->setAutoFillBackground(false);
        frame_10->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/back.png);\n"
" "));
        frame_10->setFrameShape(QFrame::Box);
        frame_10->setFrameShadow(QFrame::Sunken);
        lbl_current_soc = new QLabel(frame_10);
        lbl_current_soc->setObjectName(QString::fromUtf8("lbl_current_soc"));
        lbl_current_soc->setGeometry(QRect(174, 12, 81, 31));
        lbl_current_soc->setFont(font2);
        lbl_current_soc->setFrameShape(QFrame::NoFrame);
        lbl_caculate_energy_4 = new QLabel(frame_10);
        lbl_caculate_energy_4->setObjectName(QString::fromUtf8("lbl_caculate_energy_4"));
        lbl_caculate_energy_4->setGeometry(QRect(255, 10, 51, 31));
        lbl_caculate_energy_4->setFont(font2);
        label_soc = new QLabel(frame_10);
        label_soc->setObjectName(QString::fromUtf8("label_soc"));
        label_soc->setGeometry(QRect(10, 15, 121, 21));
        label_soc->setFont(font3);
        frame_14 = new QFrame(frame_5);
        frame_14->setObjectName(QString::fromUtf8("frame_14"));
        frame_14->setGeometry(QRect(20, 247, 301, 51));
        sizePolicy.setHeightForWidth(frame_14->sizePolicy().hasHeightForWidth());
        frame_14->setSizePolicy(sizePolicy);
        frame_14->setMinimumSize(QSize(13, 0));
        frame_14->setFont(font1);
        frame_14->setAutoFillBackground(false);
        frame_14->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/back.png);\n"
" "));
        frame_14->setFrameShape(QFrame::Box);
        frame_14->setFrameShadow(QFrame::Sunken);
        label_hightemp = new QLabel(frame_14);
        label_hightemp->setObjectName(QString::fromUtf8("label_hightemp"));
        label_hightemp->setGeometry(QRect(10, 15, 141, 21));
        label_hightemp->setFont(font3);
        lbl_time_hour_7 = new QLabel(frame_14);
        lbl_time_hour_7->setObjectName(QString::fromUtf8("lbl_time_hour_7"));
        lbl_time_hour_7->setGeometry(QRect(245, 12, 31, 31));
        lbl_time_hour_7->setFont(font2);
        lbl_h_temp = new QLabel(frame_14);
        lbl_h_temp->setObjectName(QString::fromUtf8("lbl_h_temp"));
        lbl_h_temp->setGeometry(QRect(175, 12, 81, 31));
        lbl_h_temp->setFont(font2);
        lbl_h_temp->setFrameShape(QFrame::NoFrame);
        frame_15 = new QFrame(frame_5);
        frame_15->setObjectName(QString::fromUtf8("frame_15"));
        frame_15->setGeometry(QRect(20, 198, 301, 51));
        sizePolicy.setHeightForWidth(frame_15->sizePolicy().hasHeightForWidth());
        frame_15->setSizePolicy(sizePolicy);
        frame_15->setMinimumSize(QSize(13, 0));
        frame_15->setFont(font1);
        frame_15->setAutoFillBackground(false);
        frame_15->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/back.png);\n"
" "));
        frame_15->setFrameShape(QFrame::Box);
        frame_15->setFrameShadow(QFrame::Sunken);
        label_lowvolt = new QLabel(frame_15);
        label_lowvolt->setObjectName(QString::fromUtf8("label_lowvolt"));
        label_lowvolt->setGeometry(QRect(10, 15, 141, 21));
        label_lowvolt->setFont(font3);
        label_card_sn_18 = new QLabel(frame_15);
        label_card_sn_18->setObjectName(QString::fromUtf8("label_card_sn_18"));
        label_card_sn_18->setGeometry(QRect(255, 12, 31, 31));
        label_card_sn_18->setFont(font2);
        lbl_l_volt = new QLabel(frame_15);
        lbl_l_volt->setObjectName(QString::fromUtf8("lbl_l_volt"));
        lbl_l_volt->setGeometry(QRect(175, 12, 81, 31));
        lbl_l_volt->setFont(font2);
        lbl_l_volt->setFrameShape(QFrame::NoFrame);
        frame_16 = new QFrame(frame_5);
        frame_16->setObjectName(QString::fromUtf8("frame_16"));
        frame_16->setGeometry(QRect(430, 198, 301, 51));
        sizePolicy.setHeightForWidth(frame_16->sizePolicy().hasHeightForWidth());
        frame_16->setSizePolicy(sizePolicy);
        frame_16->setMinimumSize(QSize(13, 0));
        frame_16->setFont(font1);
        frame_16->setAutoFillBackground(false);
        frame_16->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/back.png);\n"
" "));
        frame_16->setFrameShape(QFrame::Box);
        frame_16->setFrameShadow(QFrame::Sunken);
        label_state_2 = new QLabel(frame_16);
        label_state_2->setObjectName(QString::fromUtf8("label_state_2"));
        label_state_2->setGeometry(QRect(10, 15, 91, 21));
        label_state_2->setFont(font3);
        label_14 = new QLabel(frame_16);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(170, 15, 121, 21));
        label_14->setFont(font4);
        label_14->setFrameShape(QFrame::NoFrame);
        label_14->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        frame_8 = new QFrame(frame_5);
        frame_8->setObjectName(QString::fromUtf8("frame_8"));
        frame_8->setGeometry(QRect(20, 99, 301, 51));
        sizePolicy.setHeightForWidth(frame_8->sizePolicy().hasHeightForWidth());
        frame_8->setSizePolicy(sizePolicy);
        frame_8->setMinimumSize(QSize(13, 0));
        frame_8->setFont(font1);
        frame_8->setAutoFillBackground(false);
        frame_8->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/back.png);\n"
" "));
        frame_8->setFrameShape(QFrame::Box);
        frame_8->setFrameShadow(QFrame::Sunken);
        lbl_left_time = new QLabel(frame_8);
        lbl_left_time->setObjectName(QString::fromUtf8("lbl_left_time"));
        lbl_left_time->setGeometry(QRect(174, 12, 81, 31));
        lbl_left_time->setFont(font2);
        lbl_left_time->setFrameShape(QFrame::NoFrame);
        lbl_1 = new QLabel(frame_8);
        lbl_1->setObjectName(QString::fromUtf8("lbl_1"));
        lbl_1->setGeometry(QRect(255, 12, 41, 31));
        lbl_1->setFont(font2);
        label_lefttime = new QLabel(frame_8);
        label_lefttime->setObjectName(QString::fromUtf8("label_lefttime"));
        label_lefttime->setGeometry(QRect(10, 15, 141, 21));
        label_lefttime->setFont(font3);
        label_phone = new QLabel(frame_4);
        label_phone->setObjectName(QString::fromUtf8("label_phone"));
        label_phone->setGeometry(QRect(460, 460, 171, 20));
        QPalette palette;
        QBrush brush(QColor(255, 255, 255, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush1(QColor(14, 14, 242, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Button, brush1);
        QBrush brush2(QColor(123, 123, 255, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Light, brush2);
        QBrush brush3(QColor(68, 68, 248, 255));
        brush3.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        QBrush brush4(QColor(7, 7, 121, 255));
        brush4.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Dark, brush4);
        QBrush brush5(QColor(9, 9, 161, 255));
        brush5.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Mid, brush5);
        QBrush brush6(QColor(0, 0, 0, 255));
        brush6.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Text, brush6);
        palette.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette.setBrush(QPalette::Active, QPalette::ButtonText, brush6);
        palette.setBrush(QPalette::Active, QPalette::Base, brush);
        palette.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette.setBrush(QPalette::Active, QPalette::Shadow, brush6);
        QBrush brush7(QColor(134, 134, 248, 255));
        brush7.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::AlternateBase, brush7);
        QBrush brush8(QColor(255, 255, 220, 255));
        brush8.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette.setBrush(QPalette::Active, QPalette::ToolTipText, brush6);
        palette.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Inactive, QPalette::Text, brush6);
        palette.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::ButtonText, brush6);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Shadow, brush6);
        palette.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush7);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush6);
        palette.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Shadow, brush6);
        palette.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush6);
        label_phone->setPalette(palette);
        QFont font5;
        font5.setPointSize(20);
        font5.setBold(true);
        font5.setWeight(75);
        label_phone->setFont(font5);
        label_phone->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/mainlab_phonenum.png);"));
        label_phone->setTextFormat(Qt::AutoText);
        label_phone_2 = new QLabel(frame_4);
        label_phone_2->setObjectName(QString::fromUtf8("label_phone_2"));
        label_phone_2->setGeometry(QRect(625, 460, 171, 20));
        QPalette palette1;
        palette1.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette1.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette1.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette1.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        palette1.setBrush(QPalette::Active, QPalette::Dark, brush4);
        palette1.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette1.setBrush(QPalette::Active, QPalette::Text, brush6);
        palette1.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette1.setBrush(QPalette::Active, QPalette::ButtonText, brush6);
        palette1.setBrush(QPalette::Active, QPalette::Base, brush);
        palette1.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette1.setBrush(QPalette::Active, QPalette::Shadow, brush6);
        palette1.setBrush(QPalette::Active, QPalette::AlternateBase, brush7);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipText, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette1.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette1.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette1.setBrush(QPalette::Inactive, QPalette::Text, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::ButtonText, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Shadow, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush7);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush6);
        palette1.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette1.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette1.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette1.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette1.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette1.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette1.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette1.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Shadow, brush6);
        palette1.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush6);
        label_phone_2->setPalette(palette1);
        label_phone_2->setFont(font5);
        label_phone_2->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/mainlab_phonenum.png);"));
        label_phone_2->setTextFormat(Qt::AutoText);
        label_logo = new QLabel(frame_4);
        label_logo->setObjectName(QString::fromUtf8("label_logo"));
        label_logo->setGeometry(QRect(170, -20, 461, 111));
        QPalette palette2;
        palette2.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette2.setBrush(QPalette::Active, QPalette::Button, brush6);
        palette2.setBrush(QPalette::Active, QPalette::Light, brush6);
        palette2.setBrush(QPalette::Active, QPalette::Midlight, brush6);
        palette2.setBrush(QPalette::Active, QPalette::Dark, brush6);
        palette2.setBrush(QPalette::Active, QPalette::Mid, brush6);
        palette2.setBrush(QPalette::Active, QPalette::Text, brush);
        palette2.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette2.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette2.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette2.setBrush(QPalette::Active, QPalette::Window, brush6);
        palette2.setBrush(QPalette::Active, QPalette::Shadow, brush6);
        palette2.setBrush(QPalette::Active, QPalette::AlternateBase, brush6);
        palette2.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette2.setBrush(QPalette::Active, QPalette::ToolTipText, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Button, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::Light, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::Midlight, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::Dark, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::Mid, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::Window, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::Shadow, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette2.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::WindowText, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::Button, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::Light, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::Midlight, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::Dark, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::Mid, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::Text, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::ButtonText, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::Base, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::Window, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::Shadow, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette2.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush6);
        label_logo->setPalette(palette2);
        QFont font6;
        font6.setPointSize(35);
        font6.setBold(true);
        font6.setWeight(75);
        label_logo->setFont(font6);
        label_logo->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/mainlab_phonenum.png);"));
        label_logo->setTextFormat(Qt::AutoText);
        label_logo->setAlignment(Qt::AlignCenter);
        label_title_2 = new QLabel(frame_4);
        label_title_2->setObjectName(QString::fromUtf8("label_title_2"));
        label_title_2->setGeometry(QRect(30, 70, 741, 61));
        QPalette palette3;
        palette3.setBrush(QPalette::Active, QPalette::WindowText, brush6);
        palette3.setBrush(QPalette::Active, QPalette::Button, brush);
        palette3.setBrush(QPalette::Active, QPalette::Light, brush);
        palette3.setBrush(QPalette::Active, QPalette::Midlight, brush);
        QBrush brush9(QColor(127, 127, 127, 255));
        brush9.setStyle(Qt::SolidPattern);
        palette3.setBrush(QPalette::Active, QPalette::Dark, brush9);
        QBrush brush10(QColor(170, 170, 170, 255));
        brush10.setStyle(Qt::SolidPattern);
        palette3.setBrush(QPalette::Active, QPalette::Mid, brush10);
        palette3.setBrush(QPalette::Active, QPalette::Text, brush6);
        palette3.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette3.setBrush(QPalette::Active, QPalette::ButtonText, brush6);
        palette3.setBrush(QPalette::Active, QPalette::Base, brush);
        palette3.setBrush(QPalette::Active, QPalette::Window, brush);
        palette3.setBrush(QPalette::Active, QPalette::Shadow, brush6);
        palette3.setBrush(QPalette::Active, QPalette::AlternateBase, brush);
        palette3.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette3.setBrush(QPalette::Active, QPalette::ToolTipText, brush6);
        palette3.setBrush(QPalette::Inactive, QPalette::WindowText, brush6);
        palette3.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Light, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Midlight, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Dark, brush9);
        palette3.setBrush(QPalette::Inactive, QPalette::Mid, brush10);
        palette3.setBrush(QPalette::Inactive, QPalette::Text, brush6);
        palette3.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::ButtonText, brush6);
        palette3.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Shadow, brush6);
        palette3.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette3.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush6);
        palette3.setBrush(QPalette::Disabled, QPalette::WindowText, brush9);
        palette3.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::Light, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::Midlight, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::Dark, brush9);
        palette3.setBrush(QPalette::Disabled, QPalette::Mid, brush10);
        palette3.setBrush(QPalette::Disabled, QPalette::Text, brush9);
        palette3.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::ButtonText, brush9);
        palette3.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::Window, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::Shadow, brush6);
        palette3.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette3.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush6);
        label_title_2->setPalette(palette3);
        QFont font7;
        font7.setPointSize(30);
        font7.setBold(true);
        font7.setWeight(75);
        label_title_2->setFont(font7);
        label_title_2->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/mainlab_phonenum.png);"));
        label_title_2->setTextFormat(Qt::AutoText);
        label_title_2->setAlignment(Qt::AlignCenter);
        label_stubnum = new QLabel(frame_4);
        label_stubnum->setObjectName(QString::fromUtf8("label_stubnum"));
        label_stubnum->setGeometry(QRect(30, 450, 171, 31));
        QPalette palette4;
        palette4.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette4.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette4.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette4.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        palette4.setBrush(QPalette::Active, QPalette::Dark, brush4);
        palette4.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette4.setBrush(QPalette::Active, QPalette::Text, brush6);
        palette4.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette4.setBrush(QPalette::Active, QPalette::ButtonText, brush6);
        palette4.setBrush(QPalette::Active, QPalette::Base, brush);
        palette4.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette4.setBrush(QPalette::Active, QPalette::Shadow, brush6);
        palette4.setBrush(QPalette::Active, QPalette::AlternateBase, brush7);
        palette4.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette4.setBrush(QPalette::Active, QPalette::ToolTipText, brush6);
        palette4.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette4.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette4.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette4.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette4.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette4.setBrush(QPalette::Inactive, QPalette::Text, brush6);
        palette4.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::ButtonText, brush6);
        palette4.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette4.setBrush(QPalette::Inactive, QPalette::Shadow, brush6);
        palette4.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush7);
        palette4.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette4.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush6);
        palette4.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette4.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette4.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette4.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette4.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette4.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette4.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette4.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette4.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette4.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette4.setBrush(QPalette::Disabled, QPalette::Shadow, brush6);
        palette4.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette4.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette4.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush6);
        label_stubnum->setPalette(palette4);
        label_stubnum->setFont(font5);
        label_stubnum->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/mainlab_phonenum.png);"));
        label_stubnum->setTextFormat(Qt::AutoText);
        label_code = new QLabel(frame_4);
        label_code->setObjectName(QString::fromUtf8("label_code"));
        label_code->setGeometry(QRect(193, 452, 251, 31));
        QPalette palette5;
        palette5.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette5.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette5.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette5.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        palette5.setBrush(QPalette::Active, QPalette::Dark, brush4);
        palette5.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette5.setBrush(QPalette::Active, QPalette::Text, brush6);
        palette5.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette5.setBrush(QPalette::Active, QPalette::ButtonText, brush6);
        palette5.setBrush(QPalette::Active, QPalette::Base, brush);
        palette5.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette5.setBrush(QPalette::Active, QPalette::Shadow, brush6);
        palette5.setBrush(QPalette::Active, QPalette::AlternateBase, brush7);
        palette5.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette5.setBrush(QPalette::Active, QPalette::ToolTipText, brush6);
        palette5.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette5.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette5.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette5.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette5.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette5.setBrush(QPalette::Inactive, QPalette::Text, brush6);
        palette5.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::ButtonText, brush6);
        palette5.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette5.setBrush(QPalette::Inactive, QPalette::Shadow, brush6);
        palette5.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush7);
        palette5.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette5.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush6);
        palette5.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette5.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette5.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette5.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette5.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette5.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette5.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette5.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette5.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::Shadow, brush6);
        palette5.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette5.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush6);
        label_code->setPalette(palette5);
        label_code->setFont(font5);
        label_code->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/mainlab_phonenum.png);"));
        label_code->setTextFormat(Qt::AutoText);

        retranslateUi(p11_charging_dialog);

        QMetaObject::connectSlotsByName(p11_charging_dialog);
    } // setupUi

    void retranslateUi(QDialog *p11_charging_dialog)
    {
        p11_charging_dialog->setWindowTitle(QApplication::translate("p11_charging_dialog", "Dialog", 0, QApplication::UnicodeUTF8));
        lbl_output_voltage->setText(QString());
        lbl_->setText(QApplication::translate("p11_charging_dialog", "V", 0, QApplication::UnicodeUTF8));
        label_volt->setText(QString());
        lbl_caculate_energy->setText(QApplication::translate("p11_charging_dialog", "0.00", 0, QApplication::UnicodeUTF8));
        lbl_caculate_energy_3->setText(QApplication::translate("p11_charging_dialog", "kwh", 0, QApplication::UnicodeUTF8));
        label_energy->setText(QString());
        label_time->setText(QApplication::translate("p11_charging_dialog", ":", 0, QApplication::UnicodeUTF8));
        lbl_time_hour_3->setText(QApplication::translate("p11_charging_dialog", "min", 0, QApplication::UnicodeUTF8));
        lbl_time_hour->setText(QApplication::translate("p11_charging_dialog", "1", 0, QApplication::UnicodeUTF8));
        lbl_time_hour_2->setText(QApplication::translate("p11_charging_dialog", "h", 0, QApplication::UnicodeUTF8));
        lbl_time_min->setText(QApplication::translate("p11_charging_dialog", "11", 0, QApplication::UnicodeUTF8));
        label_state->setText(QString());
        lbl_chg_cur_stat->setText(QString());
        lbl_ouput_current->setText(QApplication::translate("p11_charging_dialog", "1.11", 0, QApplication::UnicodeUTF8));
        label_card_sn_16->setText(QApplication::translate("p11_charging_dialog", "A", 0, QApplication::UnicodeUTF8));
        label_current->setText(QString());
        label_equipment->setText(QString());
        label_moudletemp->setText(QApplication::translate("p11_charging_dialog", ":", 0, QApplication::UnicodeUTF8));
        lbl_time_hour_6->setText(QApplication::translate("p11_charging_dialog", "\342\204\203", 0, QApplication::UnicodeUTF8));
        lbl_h_moudle->setText(QApplication::translate("p11_charging_dialog", "1.11", 0, QApplication::UnicodeUTF8));
        lbl_h_volt->setText(QApplication::translate("p11_charging_dialog", "1.11", 0, QApplication::UnicodeUTF8));
        label_card_sn_17->setText(QApplication::translate("p11_charging_dialog", "V", 0, QApplication::UnicodeUTF8));
        label_highvlot->setText(QString());
        lbl_current_soc->setText(QApplication::translate("p11_charging_dialog", "0.00", 0, QApplication::UnicodeUTF8));
        lbl_caculate_energy_4->setText(QApplication::translate("p11_charging_dialog", "%", 0, QApplication::UnicodeUTF8));
        label_soc->setText(QString());
        label_hightemp->setText(QApplication::translate("p11_charging_dialog", ":", 0, QApplication::UnicodeUTF8));
        lbl_time_hour_7->setText(QApplication::translate("p11_charging_dialog", "\342\204\203", 0, QApplication::UnicodeUTF8));
        lbl_h_temp->setText(QApplication::translate("p11_charging_dialog", "1.11", 0, QApplication::UnicodeUTF8));
        label_lowvolt->setText(QString());
        label_card_sn_18->setText(QApplication::translate("p11_charging_dialog", "V", 0, QApplication::UnicodeUTF8));
        lbl_l_volt->setText(QApplication::translate("p11_charging_dialog", "1.11", 0, QApplication::UnicodeUTF8));
        label_state_2->setText(QString());
        label_14->setText(QString());
        lbl_left_time->setText(QString());
        lbl_1->setText(QApplication::translate("p11_charging_dialog", "min", 0, QApplication::UnicodeUTF8));
        label_lefttime->setText(QString());
        label_phone->setText(QString());
        label_phone_2->setText(QString());
        label_logo->setText(QApplication::translate("p11_charging_dialog", "DC charging pile", 0, QApplication::UnicodeUTF8));
        label_title_2->setText(QString());
        label_stubnum->setText(QString());
        label_code->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class p11_charging_dialog: public Ui_p11_charging_dialog {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_P11_CHARGING_DIALOG_H
