/********************************************************************************
** Form generated from reading UI file 'p12_payoff_dialog.ui'
**
** Created: Wed Dec 31 14:57:40 2014
**      by: Qt User Interface Compiler version 4.8.4
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_P12_PAYOFF_DIALOG_H
#define UI_P12_PAYOFF_DIALOG_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QDialog>
#include <QtGui/QFrame>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QPushButton>

QT_BEGIN_NAMESPACE

class Ui_p12_payoff_dialog
{
public:
    QFrame *frame_8;
    QFrame *frame_7;
    QPushButton *pbtn_cancel;
    QLabel *lbl_result;
    QLabel *lbl_time_hour_3;
    QLabel *lbl_time_min;
    QLabel *label_time;
    QLabel *lbl_chg_time_12;
    QLabel *lbl_money_service;
    QLabel *label_server;
    QLabel *lbl_chg_time_10;
    QLabel *lbl_caclulate_energy;
    QLabel *label_energy;
    QLabel *lbl_stop_soc;
    QLabel *label_soc;
    QLabel *lbl_chg_time_11;
    QLabel *label_elec;
    QLabel *lbl_money_electric;
    QLabel *lbl_chg_time_13;
    QLabel *label_total;
    QLabel *lbl_money_total;
    QLabel *lbl_stop_soc_2;
    QLabel *label_phone;
    QLabel *label_phone_2;
    QLabel *label_title_2;
    QLabel *label_logo;
    QLabel *label_stubnum;
    QLabel *label_code;

    void setupUi(QDialog *p12_payoff_dialog)
    {
        if (p12_payoff_dialog->objectName().isEmpty())
            p12_payoff_dialog->setObjectName(QString::fromUtf8("p12_payoff_dialog"));
        p12_payoff_dialog->resize(800, 480);
        p12_payoff_dialog->setStyleSheet(QString::fromUtf8(""));
        frame_8 = new QFrame(p12_payoff_dialog);
        frame_8->setObjectName(QString::fromUtf8("frame_8"));
        frame_8->setGeometry(QRect(0, 0, 800, 480));
        frame_8->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/PICS/backgroud_1.png);"));
        frame_8->setFrameShape(QFrame::StyledPanel);
        frame_8->setFrameShadow(QFrame::Raised);
        frame_7 = new QFrame(frame_8);
        frame_7->setObjectName(QString::fromUtf8("frame_7"));
        frame_7->setGeometry(QRect(20, 80, 761, 371));
        QFont font;
        font.setPointSize(6);
        frame_7->setFont(font);
        frame_7->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/back.png);"));
        frame_7->setFrameShape(QFrame::NoFrame);
        frame_7->setFrameShadow(QFrame::Raised);
        pbtn_cancel = new QPushButton(frame_7);
        pbtn_cancel->setObjectName(QString::fromUtf8("pbtn_cancel"));
        pbtn_cancel->setGeometry(QRect(310, 300, 141, 61));
        QPalette palette;
        QBrush brush(QColor(255, 255, 255, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush1(QColor(0, 0, 0, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette.setBrush(QPalette::Active, QPalette::Light, brush1);
        palette.setBrush(QPalette::Active, QPalette::Midlight, brush1);
        palette.setBrush(QPalette::Active, QPalette::Dark, brush1);
        palette.setBrush(QPalette::Active, QPalette::Mid, brush1);
        palette.setBrush(QPalette::Active, QPalette::Text, brush);
        palette.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette.setBrush(QPalette::Active, QPalette::Shadow, brush1);
        palette.setBrush(QPalette::Active, QPalette::AlternateBase, brush1);
        QBrush brush2(QColor(255, 255, 220, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::ToolTipBase, brush2);
        palette.setBrush(QPalette::Active, QPalette::ToolTipText, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Light, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Midlight, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Dark, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Mid, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Shadow, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Light, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Midlight, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Dark, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Mid, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Shadow, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush1);
        pbtn_cancel->setPalette(palette);
        QFont font1;
        font1.setPointSize(18);
        pbtn_cancel->setFont(font1);
        pbtn_cancel->setFocusPolicy(Qt::NoFocus);
        pbtn_cancel->setStyleSheet(QString::fromUtf8("border-image: url(:/btn/qrc/PICS/button.png);"));
        lbl_result = new QLabel(frame_7);
        lbl_result->setObjectName(QString::fromUtf8("lbl_result"));
        lbl_result->setGeometry(QRect(40, 300, 161, 51));
        QPalette palette1;
        QBrush brush3(QColor(255, 0, 0, 255));
        brush3.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::WindowText, brush3);
        palette1.setBrush(QPalette::Inactive, QPalette::WindowText, brush3);
        QBrush brush4(QColor(159, 158, 158, 255));
        brush4.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        lbl_result->setPalette(palette1);
        QFont font2;
        font2.setPointSize(25);
        lbl_result->setFont(font2);
        lbl_time_hour_3 = new QLabel(frame_7);
        lbl_time_hour_3->setObjectName(QString::fromUtf8("lbl_time_hour_3"));
        lbl_time_hour_3->setGeometry(QRect(670, 216, 51, 31));
        QFont font3;
        font3.setFamily(QString::fromUtf8("Courier 10 Pitch"));
        font3.setPointSize(25);
        font3.setBold(false);
        font3.setItalic(false);
        font3.setWeight(50);
        font3.setKerning(true);
        lbl_time_hour_3->setFont(font3);
        lbl_time_min = new QLabel(frame_7);
        lbl_time_min->setObjectName(QString::fromUtf8("lbl_time_min"));
        lbl_time_min->setGeometry(QRect(580, 216, 61, 31));
        lbl_time_min->setFont(font3);
        lbl_time_min->setFrameShape(QFrame::StyledPanel);
        lbl_time_min->setAlignment(Qt::AlignCenter);
        label_time = new QLabel(frame_7);
        label_time->setObjectName(QString::fromUtf8("label_time"));
        label_time->setGeometry(QRect(410, 210, 151, 41));
        QFont font4;
        font4.setPointSize(25);
        font4.setItalic(false);
        label_time->setFont(font4);
        lbl_chg_time_12 = new QLabel(frame_7);
        lbl_chg_time_12->setObjectName(QString::fromUtf8("lbl_chg_time_12"));
        lbl_chg_time_12->setGeometry(QRect(310, 76, 51, 31));
        lbl_chg_time_12->setFont(font3);
        lbl_money_service = new QLabel(frame_7);
        lbl_money_service->setObjectName(QString::fromUtf8("lbl_money_service"));
        lbl_money_service->setGeometry(QRect(220, 76, 61, 31));
        lbl_money_service->setFont(font3);
        lbl_money_service->setFrameShape(QFrame::StyledPanel);
        lbl_money_service->setAlignment(Qt::AlignCenter);
        label_server = new QLabel(frame_7);
        label_server->setObjectName(QString::fromUtf8("label_server"));
        label_server->setGeometry(QRect(40, 70, 151, 41));
        label_server->setFont(font4);
        lbl_chg_time_10 = new QLabel(frame_7);
        lbl_chg_time_10->setObjectName(QString::fromUtf8("lbl_chg_time_10"));
        lbl_chg_time_10->setGeometry(QRect(670, 76, 51, 31));
        lbl_chg_time_10->setFont(font3);
        lbl_caclulate_energy = new QLabel(frame_7);
        lbl_caclulate_energy->setObjectName(QString::fromUtf8("lbl_caclulate_energy"));
        lbl_caclulate_energy->setGeometry(QRect(580, 76, 61, 31));
        lbl_caclulate_energy->setFont(font3);
        lbl_caclulate_energy->setFrameShape(QFrame::StyledPanel);
        lbl_caclulate_energy->setAlignment(Qt::AlignCenter);
        label_energy = new QLabel(frame_7);
        label_energy->setObjectName(QString::fromUtf8("label_energy"));
        label_energy->setGeometry(QRect(410, 70, 151, 41));
        label_energy->setFont(font4);
        lbl_stop_soc = new QLabel(frame_7);
        lbl_stop_soc->setObjectName(QString::fromUtf8("lbl_stop_soc"));
        lbl_stop_soc->setGeometry(QRect(580, 146, 61, 31));
        lbl_stop_soc->setFont(font3);
        lbl_stop_soc->setFrameShape(QFrame::StyledPanel);
        lbl_stop_soc->setAlignment(Qt::AlignCenter);
        label_soc = new QLabel(frame_7);
        label_soc->setObjectName(QString::fromUtf8("label_soc"));
        label_soc->setGeometry(QRect(410, 140, 151, 41));
        label_soc->setFont(font4);
        lbl_chg_time_11 = new QLabel(frame_7);
        lbl_chg_time_11->setObjectName(QString::fromUtf8("lbl_chg_time_11"));
        lbl_chg_time_11->setGeometry(QRect(310, 146, 31, 31));
        lbl_chg_time_11->setFont(font3);
        label_elec = new QLabel(frame_7);
        label_elec->setObjectName(QString::fromUtf8("label_elec"));
        label_elec->setGeometry(QRect(40, 140, 151, 41));
        label_elec->setFont(font4);
        lbl_money_electric = new QLabel(frame_7);
        lbl_money_electric->setObjectName(QString::fromUtf8("lbl_money_electric"));
        lbl_money_electric->setGeometry(QRect(220, 146, 61, 31));
        lbl_money_electric->setFont(font3);
        lbl_money_electric->setFrameShape(QFrame::StyledPanel);
        lbl_money_electric->setAlignment(Qt::AlignCenter);
        lbl_chg_time_13 = new QLabel(frame_7);
        lbl_chg_time_13->setObjectName(QString::fromUtf8("lbl_chg_time_13"));
        lbl_chg_time_13->setGeometry(QRect(310, 216, 31, 31));
        lbl_chg_time_13->setFont(font3);
        label_total = new QLabel(frame_7);
        label_total->setObjectName(QString::fromUtf8("label_total"));
        label_total->setGeometry(QRect(40, 210, 151, 41));
        label_total->setFont(font4);
        lbl_money_total = new QLabel(frame_7);
        lbl_money_total->setObjectName(QString::fromUtf8("lbl_money_total"));
        lbl_money_total->setGeometry(QRect(220, 216, 61, 31));
        lbl_money_total->setFont(font3);
        lbl_money_total->setFrameShape(QFrame::StyledPanel);
        lbl_money_total->setAlignment(Qt::AlignCenter);
        lbl_stop_soc_2 = new QLabel(frame_7);
        lbl_stop_soc_2->setObjectName(QString::fromUtf8("lbl_stop_soc_2"));
        lbl_stop_soc_2->setGeometry(QRect(670, 146, 61, 31));
        lbl_stop_soc_2->setFont(font3);
        lbl_stop_soc_2->setFrameShape(QFrame::NoFrame);
        lbl_stop_soc_2->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_phone = new QLabel(frame_8);
        label_phone->setObjectName(QString::fromUtf8("label_phone"));
        label_phone->setGeometry(QRect(460, 460, 171, 20));
        QPalette palette2;
        palette2.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush5(QColor(14, 14, 242, 255));
        brush5.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Button, brush5);
        QBrush brush6(QColor(123, 123, 255, 255));
        brush6.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Light, brush6);
        QBrush brush7(QColor(68, 68, 248, 255));
        brush7.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Midlight, brush7);
        QBrush brush8(QColor(7, 7, 121, 255));
        brush8.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Dark, brush8);
        QBrush brush9(QColor(9, 9, 161, 255));
        brush9.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Mid, brush9);
        palette2.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette2.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette2.setBrush(QPalette::Active, QPalette::ButtonText, brush1);
        palette2.setBrush(QPalette::Active, QPalette::Base, brush);
        palette2.setBrush(QPalette::Active, QPalette::Window, brush5);
        palette2.setBrush(QPalette::Active, QPalette::Shadow, brush1);
        QBrush brush10(QColor(134, 134, 248, 255));
        brush10.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::AlternateBase, brush10);
        palette2.setBrush(QPalette::Active, QPalette::ToolTipBase, brush2);
        palette2.setBrush(QPalette::Active, QPalette::ToolTipText, brush1);
        palette2.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Button, brush5);
        palette2.setBrush(QPalette::Inactive, QPalette::Light, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::Midlight, brush7);
        palette2.setBrush(QPalette::Inactive, QPalette::Dark, brush8);
        palette2.setBrush(QPalette::Inactive, QPalette::Mid, brush9);
        palette2.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette2.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::ButtonText, brush1);
        palette2.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Window, brush5);
        palette2.setBrush(QPalette::Inactive, QPalette::Shadow, brush1);
        palette2.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush10);
        palette2.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush2);
        palette2.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::WindowText, brush8);
        palette2.setBrush(QPalette::Disabled, QPalette::Button, brush5);
        palette2.setBrush(QPalette::Disabled, QPalette::Light, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::Midlight, brush7);
        palette2.setBrush(QPalette::Disabled, QPalette::Dark, brush8);
        palette2.setBrush(QPalette::Disabled, QPalette::Mid, brush9);
        palette2.setBrush(QPalette::Disabled, QPalette::Text, brush8);
        palette2.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::ButtonText, brush8);
        palette2.setBrush(QPalette::Disabled, QPalette::Base, brush5);
        palette2.setBrush(QPalette::Disabled, QPalette::Window, brush5);
        palette2.setBrush(QPalette::Disabled, QPalette::Shadow, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush5);
        palette2.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush2);
        palette2.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush1);
        label_phone->setPalette(palette2);
        QFont font5;
        font5.setPointSize(20);
        font5.setBold(true);
        font5.setWeight(75);
        label_phone->setFont(font5);
        label_phone->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/mainlab_phonenum.png);"));
        label_phone->setTextFormat(Qt::AutoText);
        label_phone_2 = new QLabel(frame_8);
        label_phone_2->setObjectName(QString::fromUtf8("label_phone_2"));
        label_phone_2->setGeometry(QRect(625, 460, 171, 20));
        QPalette palette3;
        palette3.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette3.setBrush(QPalette::Active, QPalette::Button, brush5);
        palette3.setBrush(QPalette::Active, QPalette::Light, brush6);
        palette3.setBrush(QPalette::Active, QPalette::Midlight, brush7);
        palette3.setBrush(QPalette::Active, QPalette::Dark, brush8);
        palette3.setBrush(QPalette::Active, QPalette::Mid, brush9);
        palette3.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette3.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette3.setBrush(QPalette::Active, QPalette::ButtonText, brush1);
        palette3.setBrush(QPalette::Active, QPalette::Base, brush);
        palette3.setBrush(QPalette::Active, QPalette::Window, brush5);
        palette3.setBrush(QPalette::Active, QPalette::Shadow, brush1);
        palette3.setBrush(QPalette::Active, QPalette::AlternateBase, brush10);
        palette3.setBrush(QPalette::Active, QPalette::ToolTipBase, brush2);
        palette3.setBrush(QPalette::Active, QPalette::ToolTipText, brush1);
        palette3.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Button, brush5);
        palette3.setBrush(QPalette::Inactive, QPalette::Light, brush6);
        palette3.setBrush(QPalette::Inactive, QPalette::Midlight, brush7);
        palette3.setBrush(QPalette::Inactive, QPalette::Dark, brush8);
        palette3.setBrush(QPalette::Inactive, QPalette::Mid, brush9);
        palette3.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette3.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::ButtonText, brush1);
        palette3.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Window, brush5);
        palette3.setBrush(QPalette::Inactive, QPalette::Shadow, brush1);
        palette3.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush10);
        palette3.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush2);
        palette3.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::WindowText, brush8);
        palette3.setBrush(QPalette::Disabled, QPalette::Button, brush5);
        palette3.setBrush(QPalette::Disabled, QPalette::Light, brush6);
        palette3.setBrush(QPalette::Disabled, QPalette::Midlight, brush7);
        palette3.setBrush(QPalette::Disabled, QPalette::Dark, brush8);
        palette3.setBrush(QPalette::Disabled, QPalette::Mid, brush9);
        palette3.setBrush(QPalette::Disabled, QPalette::Text, brush8);
        palette3.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::ButtonText, brush8);
        palette3.setBrush(QPalette::Disabled, QPalette::Base, brush5);
        palette3.setBrush(QPalette::Disabled, QPalette::Window, brush5);
        palette3.setBrush(QPalette::Disabled, QPalette::Shadow, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush5);
        palette3.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush2);
        palette3.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush1);
        label_phone_2->setPalette(palette3);
        label_phone_2->setFont(font5);
        label_phone_2->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/mainlab_phonenum.png);"));
        label_phone_2->setTextFormat(Qt::AutoText);
        label_title_2 = new QLabel(frame_8);
        label_title_2->setObjectName(QString::fromUtf8("label_title_2"));
        label_title_2->setGeometry(QRect(30, 80, 741, 61));
        QPalette palette4;
        palette4.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette4.setBrush(QPalette::Active, QPalette::Button, brush);
        palette4.setBrush(QPalette::Active, QPalette::Light, brush);
        palette4.setBrush(QPalette::Active, QPalette::Midlight, brush);
        QBrush brush11(QColor(127, 127, 127, 255));
        brush11.setStyle(Qt::SolidPattern);
        palette4.setBrush(QPalette::Active, QPalette::Dark, brush11);
        QBrush brush12(QColor(170, 170, 170, 255));
        brush12.setStyle(Qt::SolidPattern);
        palette4.setBrush(QPalette::Active, QPalette::Mid, brush12);
        palette4.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette4.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette4.setBrush(QPalette::Active, QPalette::ButtonText, brush1);
        palette4.setBrush(QPalette::Active, QPalette::Base, brush);
        palette4.setBrush(QPalette::Active, QPalette::Window, brush);
        palette4.setBrush(QPalette::Active, QPalette::Shadow, brush1);
        palette4.setBrush(QPalette::Active, QPalette::AlternateBase, brush);
        palette4.setBrush(QPalette::Active, QPalette::ToolTipBase, brush2);
        palette4.setBrush(QPalette::Active, QPalette::ToolTipText, brush1);
        palette4.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette4.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Light, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Midlight, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Dark, brush11);
        palette4.setBrush(QPalette::Inactive, QPalette::Mid, brush12);
        palette4.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette4.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::ButtonText, brush1);
        palette4.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Shadow, brush1);
        palette4.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush2);
        palette4.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush1);
        palette4.setBrush(QPalette::Disabled, QPalette::WindowText, brush11);
        palette4.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::Light, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::Midlight, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::Dark, brush11);
        palette4.setBrush(QPalette::Disabled, QPalette::Mid, brush12);
        palette4.setBrush(QPalette::Disabled, QPalette::Text, brush11);
        palette4.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::ButtonText, brush11);
        palette4.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::Window, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::Shadow, brush1);
        palette4.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush2);
        palette4.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush1);
        label_title_2->setPalette(palette4);
        QFont font6;
        font6.setPointSize(35);
        font6.setBold(true);
        font6.setWeight(75);
        label_title_2->setFont(font6);
        label_title_2->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/mainlab_phonenum.png);"));
        label_title_2->setTextFormat(Qt::AutoText);
        label_title_2->setAlignment(Qt::AlignCenter);
        label_logo = new QLabel(frame_8);
        label_logo->setObjectName(QString::fromUtf8("label_logo"));
        label_logo->setGeometry(QRect(170, -20, 461, 111));
        QPalette palette5;
        palette5.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette5.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette5.setBrush(QPalette::Active, QPalette::Light, brush1);
        palette5.setBrush(QPalette::Active, QPalette::Midlight, brush1);
        palette5.setBrush(QPalette::Active, QPalette::Dark, brush1);
        palette5.setBrush(QPalette::Active, QPalette::Mid, brush1);
        palette5.setBrush(QPalette::Active, QPalette::Text, brush);
        palette5.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette5.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette5.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette5.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette5.setBrush(QPalette::Active, QPalette::Shadow, brush1);
        palette5.setBrush(QPalette::Active, QPalette::AlternateBase, brush1);
        palette5.setBrush(QPalette::Active, QPalette::ToolTipBase, brush2);
        palette5.setBrush(QPalette::Active, QPalette::ToolTipText, brush1);
        palette5.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette5.setBrush(QPalette::Inactive, QPalette::Light, brush1);
        palette5.setBrush(QPalette::Inactive, QPalette::Midlight, brush1);
        palette5.setBrush(QPalette::Inactive, QPalette::Dark, brush1);
        palette5.setBrush(QPalette::Inactive, QPalette::Mid, brush1);
        palette5.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette5.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette5.setBrush(QPalette::Inactive, QPalette::Shadow, brush1);
        palette5.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush1);
        palette5.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush2);
        palette5.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::Light, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::Midlight, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::Dark, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::Mid, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette5.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::Shadow, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush2);
        palette5.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush1);
        label_logo->setPalette(palette5);
        label_logo->setFont(font6);
        label_logo->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/mainlab_phonenum.png);"));
        label_logo->setTextFormat(Qt::AutoText);
        label_logo->setAlignment(Qt::AlignCenter);
        label_stubnum = new QLabel(frame_8);
        label_stubnum->setObjectName(QString::fromUtf8("label_stubnum"));
        label_stubnum->setGeometry(QRect(30, 450, 171, 31));
        QPalette palette6;
        palette6.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette6.setBrush(QPalette::Active, QPalette::Button, brush5);
        palette6.setBrush(QPalette::Active, QPalette::Light, brush6);
        palette6.setBrush(QPalette::Active, QPalette::Midlight, brush7);
        palette6.setBrush(QPalette::Active, QPalette::Dark, brush8);
        palette6.setBrush(QPalette::Active, QPalette::Mid, brush9);
        palette6.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette6.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette6.setBrush(QPalette::Active, QPalette::ButtonText, brush1);
        palette6.setBrush(QPalette::Active, QPalette::Base, brush);
        palette6.setBrush(QPalette::Active, QPalette::Window, brush5);
        palette6.setBrush(QPalette::Active, QPalette::Shadow, brush1);
        palette6.setBrush(QPalette::Active, QPalette::AlternateBase, brush10);
        palette6.setBrush(QPalette::Active, QPalette::ToolTipBase, brush2);
        palette6.setBrush(QPalette::Active, QPalette::ToolTipText, brush1);
        palette6.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::Button, brush5);
        palette6.setBrush(QPalette::Inactive, QPalette::Light, brush6);
        palette6.setBrush(QPalette::Inactive, QPalette::Midlight, brush7);
        palette6.setBrush(QPalette::Inactive, QPalette::Dark, brush8);
        palette6.setBrush(QPalette::Inactive, QPalette::Mid, brush9);
        palette6.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette6.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::ButtonText, brush1);
        palette6.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::Window, brush5);
        palette6.setBrush(QPalette::Inactive, QPalette::Shadow, brush1);
        palette6.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush10);
        palette6.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush2);
        palette6.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush1);
        palette6.setBrush(QPalette::Disabled, QPalette::WindowText, brush8);
        palette6.setBrush(QPalette::Disabled, QPalette::Button, brush5);
        palette6.setBrush(QPalette::Disabled, QPalette::Light, brush6);
        palette6.setBrush(QPalette::Disabled, QPalette::Midlight, brush7);
        palette6.setBrush(QPalette::Disabled, QPalette::Dark, brush8);
        palette6.setBrush(QPalette::Disabled, QPalette::Mid, brush9);
        palette6.setBrush(QPalette::Disabled, QPalette::Text, brush8);
        palette6.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette6.setBrush(QPalette::Disabled, QPalette::ButtonText, brush8);
        palette6.setBrush(QPalette::Disabled, QPalette::Base, brush5);
        palette6.setBrush(QPalette::Disabled, QPalette::Window, brush5);
        palette6.setBrush(QPalette::Disabled, QPalette::Shadow, brush1);
        palette6.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush5);
        palette6.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush2);
        palette6.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush1);
        label_stubnum->setPalette(palette6);
        label_stubnum->setFont(font5);
        label_stubnum->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/mainlab_phonenum.png);"));
        label_stubnum->setTextFormat(Qt::AutoText);
        label_code = new QLabel(frame_8);
        label_code->setObjectName(QString::fromUtf8("label_code"));
        label_code->setGeometry(QRect(193, 452, 251, 31));
        QPalette palette7;
        palette7.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette7.setBrush(QPalette::Active, QPalette::Button, brush5);
        palette7.setBrush(QPalette::Active, QPalette::Light, brush6);
        palette7.setBrush(QPalette::Active, QPalette::Midlight, brush7);
        palette7.setBrush(QPalette::Active, QPalette::Dark, brush8);
        palette7.setBrush(QPalette::Active, QPalette::Mid, brush9);
        palette7.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette7.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette7.setBrush(QPalette::Active, QPalette::ButtonText, brush1);
        palette7.setBrush(QPalette::Active, QPalette::Base, brush);
        palette7.setBrush(QPalette::Active, QPalette::Window, brush5);
        palette7.setBrush(QPalette::Active, QPalette::Shadow, brush1);
        palette7.setBrush(QPalette::Active, QPalette::AlternateBase, brush10);
        palette7.setBrush(QPalette::Active, QPalette::ToolTipBase, brush2);
        palette7.setBrush(QPalette::Active, QPalette::ToolTipText, brush1);
        palette7.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::Button, brush5);
        palette7.setBrush(QPalette::Inactive, QPalette::Light, brush6);
        palette7.setBrush(QPalette::Inactive, QPalette::Midlight, brush7);
        palette7.setBrush(QPalette::Inactive, QPalette::Dark, brush8);
        palette7.setBrush(QPalette::Inactive, QPalette::Mid, brush9);
        palette7.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette7.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::ButtonText, brush1);
        palette7.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::Window, brush5);
        palette7.setBrush(QPalette::Inactive, QPalette::Shadow, brush1);
        palette7.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush10);
        palette7.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush2);
        palette7.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush1);
        palette7.setBrush(QPalette::Disabled, QPalette::WindowText, brush8);
        palette7.setBrush(QPalette::Disabled, QPalette::Button, brush5);
        palette7.setBrush(QPalette::Disabled, QPalette::Light, brush6);
        palette7.setBrush(QPalette::Disabled, QPalette::Midlight, brush7);
        palette7.setBrush(QPalette::Disabled, QPalette::Dark, brush8);
        palette7.setBrush(QPalette::Disabled, QPalette::Mid, brush9);
        palette7.setBrush(QPalette::Disabled, QPalette::Text, brush8);
        palette7.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette7.setBrush(QPalette::Disabled, QPalette::ButtonText, brush8);
        palette7.setBrush(QPalette::Disabled, QPalette::Base, brush5);
        palette7.setBrush(QPalette::Disabled, QPalette::Window, brush5);
        palette7.setBrush(QPalette::Disabled, QPalette::Shadow, brush1);
        palette7.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush5);
        palette7.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush2);
        palette7.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush1);
        label_code->setPalette(palette7);
        label_code->setFont(font5);
        label_code->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/mainlab_phonenum.png);"));
        label_code->setTextFormat(Qt::AutoText);

        retranslateUi(p12_payoff_dialog);

        QMetaObject::connectSlotsByName(p12_payoff_dialog);
    } // setupUi

    void retranslateUi(QDialog *p12_payoff_dialog)
    {
        p12_payoff_dialog->setWindowTitle(QApplication::translate("p12_payoff_dialog", "Dialog", 0, QApplication::UnicodeUTF8));
        pbtn_cancel->setText(QString());
        lbl_result->setText(QString());
        lbl_time_hour_3->setText(QApplication::translate("p12_payoff_dialog", "min", 0, QApplication::UnicodeUTF8));
        lbl_time_min->setText(QApplication::translate("p12_payoff_dialog", "00", 0, QApplication::UnicodeUTF8));
        label_time->setText(QApplication::translate("p12_payoff_dialog", "\345\205\205\347\224\265\346\234\215\345\212\241\346\227\266\351\227\264:", 0, QApplication::UnicodeUTF8));
        lbl_chg_time_12->setText(QApplication::translate("p12_payoff_dialog", "\302\245", 0, QApplication::UnicodeUTF8));
        lbl_money_service->setText(QApplication::translate("p12_payoff_dialog", "0.0", 0, QApplication::UnicodeUTF8));
        label_server->setText(QApplication::translate("p12_payoff_dialog", "\345\205\205\347\224\265\346\234\215\345\212\241\350\264\271:", 0, QApplication::UnicodeUTF8));
        lbl_chg_time_10->setText(QApplication::translate("p12_payoff_dialog", "kwh", 0, QApplication::UnicodeUTF8));
        lbl_caclulate_energy->setText(QApplication::translate("p12_payoff_dialog", "0.00", 0, QApplication::UnicodeUTF8));
        label_energy->setText(QApplication::translate("p12_payoff_dialog", "\346\266\210\350\200\227\347\224\265\351\207\217:", 0, QApplication::UnicodeUTF8));
        lbl_stop_soc->setText(QApplication::translate("p12_payoff_dialog", "1", 0, QApplication::UnicodeUTF8));
        label_soc->setText(QApplication::translate("p12_payoff_dialog", ":", 0, QApplication::UnicodeUTF8));
        lbl_chg_time_11->setText(QApplication::translate("p12_payoff_dialog", "\302\245", 0, QApplication::UnicodeUTF8));
        label_elec->setText(QApplication::translate("p12_payoff_dialog", "\344\273\243\346\224\266\347\224\265\350\264\271:", 0, QApplication::UnicodeUTF8));
        lbl_money_electric->setText(QString());
        lbl_chg_time_13->setText(QApplication::translate("p12_payoff_dialog", "\302\245", 0, QApplication::UnicodeUTF8));
        label_total->setText(QApplication::translate("p12_payoff_dialog", "\350\264\271\346\200\273\351\207\221\351\242\235:", 0, QApplication::UnicodeUTF8));
        lbl_money_total->setText(QApplication::translate("p12_payoff_dialog", "0.00", 0, QApplication::UnicodeUTF8));
        lbl_stop_soc_2->setText(QApplication::translate("p12_payoff_dialog", "%", 0, QApplication::UnicodeUTF8));
        label_phone->setText(QString());
        label_phone_2->setText(QString());
        label_title_2->setText(QString());
        label_logo->setText(QApplication::translate("p12_payoff_dialog", "DC charging pile", 0, QApplication::UnicodeUTF8));
        label_stubnum->setText(QString());
        label_code->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class p12_payoff_dialog: public Ui_p12_payoff_dialog {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_P12_PAYOFF_DIALOG_H
