/********************************************************************************
** Form generated from reading UI file 'p22_elecprice_dialog.ui'
**
** Created: Sat Jan 3 11:22:06 2015
**      by: Qt User Interface Compiler version 4.8.4
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_P22_ELECPRICE_DIALOG_H
#define UI_P22_ELECPRICE_DIALOG_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QDialog>
#include <QtGui/QFrame>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QPushButton>

QT_BEGIN_NAMESPACE

class Ui_p22_ElecPrice_dialog
{
public:
    QFrame *p22_ElecPrice_dialog_2;
    QLabel *label_phone;
    QLabel *label_phone_2;
    QLabel *label_title;
    QPushButton *pbtn_cancel;
    QLabel *label_code;
    QLabel *label_stubnum;
    QLabel *label_logo;
    QFrame *frame;
    QLabel *label_f1;
    QLabel *label_4;
    QLabel *label_3;
    QLabel *label_2;
    QLabel *label_t1;
    QLabel *label_p1;
    QLabel *label_5;
    QLabel *label_g1;
    QLabel *lbl_chg_time_12;
    QLabel *lbl_chg_time_13;
    QLabel *lbl_chg_time_14;
    QLabel *lbl_chg_time_15;
    QLabel *label_t1_1;
    QLabel *label_t1_2;
    QLabel *label_p1_1;
    QLabel *label_p1_2;
    QLabel *label_f1_1;
    QLabel *label_f1_2;
    QLabel *label_g1_1;
    QLabel *label_g1_2;
    QFrame *frame_2;
    QLabel *label_f2;
    QLabel *label_6;
    QLabel *label_7;
    QLabel *label_8;
    QLabel *label_t2;
    QLabel *label_p2;
    QLabel *label_9;
    QLabel *label_g2;
    QLabel *lbl_chg_time_16;
    QLabel *lbl_chg_time_17;
    QLabel *lbl_chg_time_18;
    QLabel *lbl_chg_time_19;
    QLabel *label_t1_3;
    QLabel *label_t1_4;
    QLabel *label_p1_3;
    QLabel *label_p1_4;
    QLabel *label_f1_3;
    QLabel *label_f1_4;
    QLabel *label_g1_3;
    QLabel *label_g1_4;

    void setupUi(QDialog *p22_ElecPrice_dialog)
    {
        if (p22_ElecPrice_dialog->objectName().isEmpty())
            p22_ElecPrice_dialog->setObjectName(QString::fromUtf8("p22_ElecPrice_dialog"));
        p22_ElecPrice_dialog->resize(800, 480);
        p22_ElecPrice_dialog_2 = new QFrame(p22_ElecPrice_dialog);
        p22_ElecPrice_dialog_2->setObjectName(QString::fromUtf8("p22_ElecPrice_dialog_2"));
        p22_ElecPrice_dialog_2->setGeometry(QRect(0, 0, 800, 480));
        QFont font;
        font.setPointSize(28);
        p22_ElecPrice_dialog_2->setFont(font);
        p22_ElecPrice_dialog_2->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/PICS/backgroud_1.png);"));
        p22_ElecPrice_dialog_2->setFrameShape(QFrame::StyledPanel);
        p22_ElecPrice_dialog_2->setFrameShadow(QFrame::Raised);
        label_phone = new QLabel(p22_ElecPrice_dialog_2);
        label_phone->setObjectName(QString::fromUtf8("label_phone"));
        label_phone->setGeometry(QRect(460, 460, 171, 20));
        QPalette palette;
        QBrush brush(QColor(255, 255, 255, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush1(QColor(14, 14, 242, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Button, brush1);
        QBrush brush2(QColor(123, 123, 255, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Light, brush2);
        QBrush brush3(QColor(68, 68, 248, 255));
        brush3.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        QBrush brush4(QColor(7, 7, 121, 255));
        brush4.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Dark, brush4);
        QBrush brush5(QColor(9, 9, 161, 255));
        brush5.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Mid, brush5);
        QBrush brush6(QColor(0, 0, 0, 255));
        brush6.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Text, brush6);
        palette.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette.setBrush(QPalette::Active, QPalette::ButtonText, brush6);
        palette.setBrush(QPalette::Active, QPalette::Base, brush);
        palette.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette.setBrush(QPalette::Active, QPalette::Shadow, brush6);
        QBrush brush7(QColor(134, 134, 248, 255));
        brush7.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::AlternateBase, brush7);
        QBrush brush8(QColor(255, 255, 220, 255));
        brush8.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette.setBrush(QPalette::Active, QPalette::ToolTipText, brush6);
        palette.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Inactive, QPalette::Text, brush6);
        palette.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::ButtonText, brush6);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Shadow, brush6);
        palette.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush7);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush6);
        palette.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Shadow, brush6);
        palette.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush6);
        label_phone->setPalette(palette);
        QFont font1;
        font1.setPointSize(20);
        font1.setBold(true);
        font1.setWeight(75);
        label_phone->setFont(font1);
        label_phone->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/mainlab_phonenum.png);"));
        label_phone->setTextFormat(Qt::AutoText);
        label_phone_2 = new QLabel(p22_ElecPrice_dialog_2);
        label_phone_2->setObjectName(QString::fromUtf8("label_phone_2"));
        label_phone_2->setGeometry(QRect(625, 460, 171, 20));
        QPalette palette1;
        palette1.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette1.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette1.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette1.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        palette1.setBrush(QPalette::Active, QPalette::Dark, brush4);
        palette1.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette1.setBrush(QPalette::Active, QPalette::Text, brush6);
        palette1.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette1.setBrush(QPalette::Active, QPalette::ButtonText, brush6);
        palette1.setBrush(QPalette::Active, QPalette::Base, brush);
        palette1.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette1.setBrush(QPalette::Active, QPalette::Shadow, brush6);
        palette1.setBrush(QPalette::Active, QPalette::AlternateBase, brush7);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipText, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette1.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette1.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette1.setBrush(QPalette::Inactive, QPalette::Text, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::ButtonText, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Shadow, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush7);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush6);
        palette1.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette1.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette1.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette1.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette1.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette1.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette1.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette1.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Shadow, brush6);
        palette1.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush6);
        label_phone_2->setPalette(palette1);
        label_phone_2->setFont(font1);
        label_phone_2->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/mainlab_phonenum.png);"));
        label_phone_2->setTextFormat(Qt::AutoText);
        label_title = new QLabel(p22_ElecPrice_dialog_2);
        label_title->setObjectName(QString::fromUtf8("label_title"));
        label_title->setGeometry(QRect(70, 80, 661, 51));
        QFont font2;
        font2.setFamily(QString::fromUtf8("Ubuntu"));
        font2.setPointSize(35);
        font2.setBold(true);
        font2.setItalic(false);
        font2.setWeight(75);
        font2.setKerning(true);
        label_title->setFont(font2);
        label_title->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/frame_white.png);"));
        label_title->setAlignment(Qt::AlignCenter);
        pbtn_cancel = new QPushButton(p22_ElecPrice_dialog_2);
        pbtn_cancel->setObjectName(QString::fromUtf8("pbtn_cancel"));
        pbtn_cancel->setGeometry(QRect(330, 390, 151, 61));
        QPalette palette2;
        palette2.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette2.setBrush(QPalette::Active, QPalette::Button, brush6);
        palette2.setBrush(QPalette::Active, QPalette::Light, brush6);
        palette2.setBrush(QPalette::Active, QPalette::Midlight, brush6);
        palette2.setBrush(QPalette::Active, QPalette::Dark, brush6);
        palette2.setBrush(QPalette::Active, QPalette::Mid, brush6);
        palette2.setBrush(QPalette::Active, QPalette::Text, brush);
        palette2.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette2.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette2.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette2.setBrush(QPalette::Active, QPalette::Window, brush6);
        palette2.setBrush(QPalette::Active, QPalette::Shadow, brush6);
        palette2.setBrush(QPalette::Active, QPalette::AlternateBase, brush6);
        palette2.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette2.setBrush(QPalette::Active, QPalette::ToolTipText, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Button, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::Light, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::Midlight, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::Dark, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::Mid, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::Window, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::Shadow, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette2.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::WindowText, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::Button, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::Light, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::Midlight, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::Dark, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::Mid, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::Text, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::ButtonText, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::Base, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::Window, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::Shadow, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette2.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush6);
        pbtn_cancel->setPalette(palette2);
        QFont font3;
        font3.setPointSize(23);
        font3.setBold(true);
        font3.setWeight(75);
        pbtn_cancel->setFont(font3);
        pbtn_cancel->setFocusPolicy(Qt::NoFocus);
        pbtn_cancel->setStyleSheet(QString::fromUtf8("border-image: url(:/btn/qrc/PICS/button.png);"));
        label_code = new QLabel(p22_ElecPrice_dialog_2);
        label_code->setObjectName(QString::fromUtf8("label_code"));
        label_code->setGeometry(QRect(193, 452, 251, 31));
        QPalette palette3;
        palette3.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette3.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette3.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette3.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        palette3.setBrush(QPalette::Active, QPalette::Dark, brush4);
        palette3.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette3.setBrush(QPalette::Active, QPalette::Text, brush6);
        palette3.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette3.setBrush(QPalette::Active, QPalette::ButtonText, brush6);
        palette3.setBrush(QPalette::Active, QPalette::Base, brush);
        palette3.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette3.setBrush(QPalette::Active, QPalette::Shadow, brush6);
        palette3.setBrush(QPalette::Active, QPalette::AlternateBase, brush7);
        palette3.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette3.setBrush(QPalette::Active, QPalette::ToolTipText, brush6);
        palette3.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette3.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette3.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette3.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette3.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette3.setBrush(QPalette::Inactive, QPalette::Text, brush6);
        palette3.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::ButtonText, brush6);
        palette3.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette3.setBrush(QPalette::Inactive, QPalette::Shadow, brush6);
        palette3.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush7);
        palette3.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette3.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush6);
        palette3.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette3.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette3.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette3.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette3.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette3.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette3.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette3.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::Shadow, brush6);
        palette3.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette3.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush6);
        label_code->setPalette(palette3);
        label_code->setFont(font1);
        label_code->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/mainlab_phonenum.png);"));
        label_code->setTextFormat(Qt::AutoText);
        label_stubnum = new QLabel(p22_ElecPrice_dialog_2);
        label_stubnum->setObjectName(QString::fromUtf8("label_stubnum"));
        label_stubnum->setGeometry(QRect(33, 450, 171, 31));
        QPalette palette4;
        palette4.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette4.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette4.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette4.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        palette4.setBrush(QPalette::Active, QPalette::Dark, brush4);
        palette4.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette4.setBrush(QPalette::Active, QPalette::Text, brush6);
        palette4.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette4.setBrush(QPalette::Active, QPalette::ButtonText, brush6);
        palette4.setBrush(QPalette::Active, QPalette::Base, brush);
        palette4.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette4.setBrush(QPalette::Active, QPalette::Shadow, brush6);
        palette4.setBrush(QPalette::Active, QPalette::AlternateBase, brush7);
        palette4.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette4.setBrush(QPalette::Active, QPalette::ToolTipText, brush6);
        palette4.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette4.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette4.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette4.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette4.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette4.setBrush(QPalette::Inactive, QPalette::Text, brush6);
        palette4.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::ButtonText, brush6);
        palette4.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette4.setBrush(QPalette::Inactive, QPalette::Shadow, brush6);
        palette4.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush7);
        palette4.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette4.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush6);
        palette4.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette4.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette4.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette4.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette4.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette4.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette4.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette4.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette4.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette4.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette4.setBrush(QPalette::Disabled, QPalette::Shadow, brush6);
        palette4.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette4.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette4.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush6);
        label_stubnum->setPalette(palette4);
        label_stubnum->setFont(font1);
        label_stubnum->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/mainlab_phonenum.png);"));
        label_stubnum->setTextFormat(Qt::AutoText);
        label_logo = new QLabel(p22_ElecPrice_dialog_2);
        label_logo->setObjectName(QString::fromUtf8("label_logo"));
        label_logo->setGeometry(QRect(160, 0, 481, 81));
        QPalette palette5;
        palette5.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette5.setBrush(QPalette::Active, QPalette::Button, brush6);
        palette5.setBrush(QPalette::Active, QPalette::Light, brush6);
        palette5.setBrush(QPalette::Active, QPalette::Midlight, brush6);
        palette5.setBrush(QPalette::Active, QPalette::Dark, brush6);
        palette5.setBrush(QPalette::Active, QPalette::Mid, brush6);
        palette5.setBrush(QPalette::Active, QPalette::Text, brush);
        palette5.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette5.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette5.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette5.setBrush(QPalette::Active, QPalette::Window, brush6);
        palette5.setBrush(QPalette::Active, QPalette::Shadow, brush6);
        palette5.setBrush(QPalette::Active, QPalette::AlternateBase, brush6);
        palette5.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette5.setBrush(QPalette::Active, QPalette::ToolTipText, brush6);
        palette5.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::Button, brush6);
        palette5.setBrush(QPalette::Inactive, QPalette::Light, brush6);
        palette5.setBrush(QPalette::Inactive, QPalette::Midlight, brush6);
        palette5.setBrush(QPalette::Inactive, QPalette::Dark, brush6);
        palette5.setBrush(QPalette::Inactive, QPalette::Mid, brush6);
        palette5.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette5.setBrush(QPalette::Inactive, QPalette::Window, brush6);
        palette5.setBrush(QPalette::Inactive, QPalette::Shadow, brush6);
        palette5.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush6);
        palette5.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette5.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush6);
        palette5.setBrush(QPalette::Disabled, QPalette::WindowText, brush6);
        palette5.setBrush(QPalette::Disabled, QPalette::Button, brush6);
        palette5.setBrush(QPalette::Disabled, QPalette::Light, brush6);
        palette5.setBrush(QPalette::Disabled, QPalette::Midlight, brush6);
        palette5.setBrush(QPalette::Disabled, QPalette::Dark, brush6);
        palette5.setBrush(QPalette::Disabled, QPalette::Mid, brush6);
        palette5.setBrush(QPalette::Disabled, QPalette::Text, brush6);
        palette5.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette5.setBrush(QPalette::Disabled, QPalette::ButtonText, brush6);
        palette5.setBrush(QPalette::Disabled, QPalette::Base, brush6);
        palette5.setBrush(QPalette::Disabled, QPalette::Window, brush6);
        palette5.setBrush(QPalette::Disabled, QPalette::Shadow, brush6);
        palette5.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush6);
        palette5.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette5.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush6);
        label_logo->setPalette(palette5);
        QFont font4;
        font4.setPointSize(40);
        font4.setBold(true);
        font4.setWeight(75);
        label_logo->setFont(font4);
        label_logo->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/mainlab_phonenum.png);"));
        label_logo->setTextFormat(Qt::AutoText);
        label_logo->setAlignment(Qt::AlignCenter);
        frame = new QFrame(p22_ElecPrice_dialog_2);
        frame->setObjectName(QString::fromUtf8("frame"));
        frame->setGeometry(QRect(30, 120, 371, 261));
        frame->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/frame_white.png);"));
        frame->setFrameShape(QFrame::NoFrame);
        frame->setFrameShadow(QFrame::Plain);
        label_f1 = new QLabel(frame);
        label_f1->setObjectName(QString::fromUtf8("label_f1"));
        label_f1->setGeometry(QRect(300, 150, 41, 41));
        label_f1->setFont(font1);
        label_f1->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/frame_white.png);"));
        label_4 = new QLabel(frame);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(130, 150, 21, 41));
        QFont font5;
        font5.setPointSize(25);
        font5.setBold(false);
        font5.setWeight(50);
        label_4->setFont(font5);
        label_4->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/frame_white.png);"));
        label_3 = new QLabel(frame);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(130, 80, 21, 41));
        label_3->setFont(font5);
        label_3->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/frame_white.png);"));
        label_2 = new QLabel(frame);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(130, 10, 21, 41));
        label_2->setFont(font5);
        label_2->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/frame_white.png);"));
        label_t1 = new QLabel(frame);
        label_t1->setObjectName(QString::fromUtf8("label_t1"));
        label_t1->setGeometry(QRect(300, 10, 41, 41));
        label_t1->setFont(font1);
        label_t1->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/frame_white.png);"));
        label_p1 = new QLabel(frame);
        label_p1->setObjectName(QString::fromUtf8("label_p1"));
        label_p1->setGeometry(QRect(300, 80, 41, 41));
        label_p1->setFont(font1);
        label_p1->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/frame_white.png);"));
        label_5 = new QLabel(frame);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(130, 220, 21, 41));
        label_5->setFont(font5);
        label_5->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/frame_white.png);"));
        label_g1 = new QLabel(frame);
        label_g1->setObjectName(QString::fromUtf8("label_g1"));
        label_g1->setGeometry(QRect(300, 220, 41, 41));
        label_g1->setFont(font1);
        label_g1->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/frame_white.png);"));
        lbl_chg_time_12 = new QLabel(frame);
        lbl_chg_time_12->setObjectName(QString::fromUtf8("lbl_chg_time_12"));
        lbl_chg_time_12->setGeometry(QRect(343, 13, 21, 41));
        QFont font6;
        font6.setFamily(QString::fromUtf8("Courier 10 Pitch"));
        font6.setPointSize(20);
        font6.setBold(true);
        font6.setItalic(false);
        font6.setWeight(75);
        font6.setKerning(true);
        lbl_chg_time_12->setFont(font6);
        lbl_chg_time_12->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/frame_white.png);"));
        lbl_chg_time_13 = new QLabel(frame);
        lbl_chg_time_13->setObjectName(QString::fromUtf8("lbl_chg_time_13"));
        lbl_chg_time_13->setGeometry(QRect(340, 83, 21, 41));
        lbl_chg_time_13->setFont(font6);
        lbl_chg_time_13->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/frame_white.png);"));
        lbl_chg_time_14 = new QLabel(frame);
        lbl_chg_time_14->setObjectName(QString::fromUtf8("lbl_chg_time_14"));
        lbl_chg_time_14->setGeometry(QRect(340, 153, 21, 41));
        lbl_chg_time_14->setFont(font6);
        lbl_chg_time_14->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/frame_white.png);"));
        lbl_chg_time_15 = new QLabel(frame);
        lbl_chg_time_15->setObjectName(QString::fromUtf8("lbl_chg_time_15"));
        lbl_chg_time_15->setGeometry(QRect(340, 223, 21, 41));
        lbl_chg_time_15->setFont(font6);
        lbl_chg_time_15->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/frame_white.png);"));
        label_t1_1 = new QLabel(frame);
        label_t1_1->setObjectName(QString::fromUtf8("label_t1_1"));
        label_t1_1->setGeometry(QRect(10, 10, 111, 41));
        label_t1_1->setFont(font1);
        label_t1_1->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/frame_white.png);"));
        label_t1_1->setAlignment(Qt::AlignCenter);
        label_t1_2 = new QLabel(frame);
        label_t1_2->setObjectName(QString::fromUtf8("label_t1_2"));
        label_t1_2->setGeometry(QRect(160, 10, 111, 41));
        label_t1_2->setFont(font1);
        label_t1_2->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/frame_white.png);"));
        label_t1_2->setAlignment(Qt::AlignCenter);
        label_p1_1 = new QLabel(frame);
        label_p1_1->setObjectName(QString::fromUtf8("label_p1_1"));
        label_p1_1->setGeometry(QRect(10, 80, 111, 41));
        label_p1_1->setFont(font1);
        label_p1_1->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/frame_white.png);"));
        label_p1_1->setAlignment(Qt::AlignCenter);
        label_p1_2 = new QLabel(frame);
        label_p1_2->setObjectName(QString::fromUtf8("label_p1_2"));
        label_p1_2->setGeometry(QRect(160, 80, 111, 41));
        label_p1_2->setFont(font1);
        label_p1_2->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/frame_white.png);"));
        label_p1_2->setAlignment(Qt::AlignCenter);
        label_f1_1 = new QLabel(frame);
        label_f1_1->setObjectName(QString::fromUtf8("label_f1_1"));
        label_f1_1->setGeometry(QRect(10, 150, 111, 41));
        label_f1_1->setFont(font1);
        label_f1_1->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/frame_white.png);"));
        label_f1_1->setAlignment(Qt::AlignCenter);
        label_f1_2 = new QLabel(frame);
        label_f1_2->setObjectName(QString::fromUtf8("label_f1_2"));
        label_f1_2->setGeometry(QRect(160, 150, 111, 41));
        label_f1_2->setFont(font1);
        label_f1_2->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/frame_white.png);"));
        label_f1_2->setAlignment(Qt::AlignCenter);
        label_g1_1 = new QLabel(frame);
        label_g1_1->setObjectName(QString::fromUtf8("label_g1_1"));
        label_g1_1->setGeometry(QRect(10, 220, 111, 41));
        label_g1_1->setFont(font1);
        label_g1_1->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/frame_white.png);"));
        label_g1_1->setAlignment(Qt::AlignCenter);
        label_g1_2 = new QLabel(frame);
        label_g1_2->setObjectName(QString::fromUtf8("label_g1_2"));
        label_g1_2->setGeometry(QRect(160, 220, 111, 41));
        label_g1_2->setFont(font1);
        label_g1_2->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/frame_white.png);"));
        label_g1_2->setAlignment(Qt::AlignCenter);
        frame_2 = new QFrame(p22_ElecPrice_dialog_2);
        frame_2->setObjectName(QString::fromUtf8("frame_2"));
        frame_2->setGeometry(QRect(400, 120, 371, 261));
        frame_2->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/frame_white.png);"));
        frame_2->setFrameShape(QFrame::NoFrame);
        frame_2->setFrameShadow(QFrame::Plain);
        label_f2 = new QLabel(frame_2);
        label_f2->setObjectName(QString::fromUtf8("label_f2"));
        label_f2->setGeometry(QRect(300, 150, 41, 41));
        label_f2->setFont(font1);
        label_f2->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/frame_white.png);"));
        label_6 = new QLabel(frame_2);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(130, 150, 21, 41));
        label_6->setFont(font5);
        label_6->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/frame_white.png);"));
        label_7 = new QLabel(frame_2);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(130, 80, 21, 41));
        label_7->setFont(font5);
        label_7->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/frame_white.png);"));
        label_8 = new QLabel(frame_2);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(130, 10, 21, 41));
        label_8->setFont(font5);
        label_8->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/frame_white.png);"));
        label_t2 = new QLabel(frame_2);
        label_t2->setObjectName(QString::fromUtf8("label_t2"));
        label_t2->setGeometry(QRect(300, 10, 41, 41));
        label_t2->setFont(font1);
        label_t2->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/frame_white.png);"));
        label_p2 = new QLabel(frame_2);
        label_p2->setObjectName(QString::fromUtf8("label_p2"));
        label_p2->setGeometry(QRect(300, 80, 41, 41));
        label_p2->setFont(font1);
        label_p2->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/frame_white.png);"));
        label_9 = new QLabel(frame_2);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(130, 220, 21, 41));
        label_9->setFont(font5);
        label_9->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/frame_white.png);"));
        label_g2 = new QLabel(frame_2);
        label_g2->setObjectName(QString::fromUtf8("label_g2"));
        label_g2->setGeometry(QRect(300, 220, 41, 41));
        label_g2->setFont(font1);
        label_g2->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/frame_white.png);"));
        lbl_chg_time_16 = new QLabel(frame_2);
        lbl_chg_time_16->setObjectName(QString::fromUtf8("lbl_chg_time_16"));
        lbl_chg_time_16->setGeometry(QRect(343, 13, 21, 41));
        lbl_chg_time_16->setFont(font6);
        lbl_chg_time_16->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/frame_white.png);"));
        lbl_chg_time_17 = new QLabel(frame_2);
        lbl_chg_time_17->setObjectName(QString::fromUtf8("lbl_chg_time_17"));
        lbl_chg_time_17->setGeometry(QRect(340, 83, 21, 41));
        lbl_chg_time_17->setFont(font6);
        lbl_chg_time_17->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/frame_white.png);"));
        lbl_chg_time_18 = new QLabel(frame_2);
        lbl_chg_time_18->setObjectName(QString::fromUtf8("lbl_chg_time_18"));
        lbl_chg_time_18->setGeometry(QRect(340, 153, 21, 41));
        lbl_chg_time_18->setFont(font6);
        lbl_chg_time_18->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/frame_white.png);"));
        lbl_chg_time_19 = new QLabel(frame_2);
        lbl_chg_time_19->setObjectName(QString::fromUtf8("lbl_chg_time_19"));
        lbl_chg_time_19->setGeometry(QRect(340, 223, 21, 41));
        lbl_chg_time_19->setFont(font6);
        lbl_chg_time_19->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/frame_white.png);"));
        label_t1_3 = new QLabel(frame_2);
        label_t1_3->setObjectName(QString::fromUtf8("label_t1_3"));
        label_t1_3->setGeometry(QRect(10, 10, 111, 41));
        label_t1_3->setFont(font1);
        label_t1_3->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/frame_white.png);"));
        label_t1_3->setAlignment(Qt::AlignCenter);
        label_t1_4 = new QLabel(frame_2);
        label_t1_4->setObjectName(QString::fromUtf8("label_t1_4"));
        label_t1_4->setGeometry(QRect(160, 10, 111, 41));
        label_t1_4->setFont(font1);
        label_t1_4->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/frame_white.png);"));
        label_t1_4->setAlignment(Qt::AlignCenter);
        label_p1_3 = new QLabel(frame_2);
        label_p1_3->setObjectName(QString::fromUtf8("label_p1_3"));
        label_p1_3->setGeometry(QRect(10, 80, 111, 41));
        label_p1_3->setFont(font1);
        label_p1_3->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/frame_white.png);"));
        label_p1_3->setAlignment(Qt::AlignCenter);
        label_p1_4 = new QLabel(frame_2);
        label_p1_4->setObjectName(QString::fromUtf8("label_p1_4"));
        label_p1_4->setGeometry(QRect(160, 80, 111, 41));
        label_p1_4->setFont(font1);
        label_p1_4->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/frame_white.png);"));
        label_p1_4->setAlignment(Qt::AlignCenter);
        label_f1_3 = new QLabel(frame_2);
        label_f1_3->setObjectName(QString::fromUtf8("label_f1_3"));
        label_f1_3->setGeometry(QRect(10, 150, 111, 41));
        label_f1_3->setFont(font1);
        label_f1_3->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/frame_white.png);"));
        label_f1_3->setAlignment(Qt::AlignCenter);
        label_f1_4 = new QLabel(frame_2);
        label_f1_4->setObjectName(QString::fromUtf8("label_f1_4"));
        label_f1_4->setGeometry(QRect(160, 150, 111, 41));
        label_f1_4->setFont(font1);
        label_f1_4->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/frame_white.png);"));
        label_f1_4->setAlignment(Qt::AlignCenter);
        label_g1_3 = new QLabel(frame_2);
        label_g1_3->setObjectName(QString::fromUtf8("label_g1_3"));
        label_g1_3->setGeometry(QRect(10, 220, 111, 41));
        label_g1_3->setFont(font1);
        label_g1_3->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/frame_white.png);"));
        label_g1_3->setAlignment(Qt::AlignCenter);
        label_g1_4 = new QLabel(frame_2);
        label_g1_4->setObjectName(QString::fromUtf8("label_g1_4"));
        label_g1_4->setGeometry(QRect(160, 220, 111, 41));
        label_g1_4->setFont(font1);
        label_g1_4->setStyleSheet(QString::fromUtf8("background-image: url(:/background/qrc/background/frame_white.png);"));
        label_g1_4->setAlignment(Qt::AlignCenter);

        retranslateUi(p22_ElecPrice_dialog);

        QMetaObject::connectSlotsByName(p22_ElecPrice_dialog);
    } // setupUi

    void retranslateUi(QDialog *p22_ElecPrice_dialog)
    {
        p22_ElecPrice_dialog->setWindowTitle(QApplication::translate("p22_ElecPrice_dialog", "Dialog", 0, QApplication::UnicodeUTF8));
        label_phone->setText(QString());
        label_phone_2->setText(QString());
        label_title->setText(QString());
        pbtn_cancel->setText(QString());
        label_code->setText(QApplication::translate("p22_ElecPrice_dialog", "0102030405060708", 0, QApplication::UnicodeUTF8));
        label_stubnum->setText(QString());
        label_logo->setText(QString());
        label_f1->setText(QApplication::translate("p22_ElecPrice_dialog", "3", 0, QApplication::UnicodeUTF8));
        label_4->setText(QApplication::translate("p22_ElecPrice_dialog", "~", 0, QApplication::UnicodeUTF8));
        label_3->setText(QApplication::translate("p22_ElecPrice_dialog", "~", 0, QApplication::UnicodeUTF8));
        label_2->setText(QApplication::translate("p22_ElecPrice_dialog", "~", 0, QApplication::UnicodeUTF8));
        label_t1->setText(QApplication::translate("p22_ElecPrice_dialog", "1.2", 0, QApplication::UnicodeUTF8));
        label_p1->setText(QApplication::translate("p22_ElecPrice_dialog", "2", 0, QApplication::UnicodeUTF8));
        label_5->setText(QApplication::translate("p22_ElecPrice_dialog", "~", 0, QApplication::UnicodeUTF8));
        label_g1->setText(QApplication::translate("p22_ElecPrice_dialog", "4", 0, QApplication::UnicodeUTF8));
        lbl_chg_time_12->setText(QApplication::translate("p22_ElecPrice_dialog", "\302\245", 0, QApplication::UnicodeUTF8));
        lbl_chg_time_13->setText(QApplication::translate("p22_ElecPrice_dialog", "\302\245", 0, QApplication::UnicodeUTF8));
        lbl_chg_time_14->setText(QApplication::translate("p22_ElecPrice_dialog", "\302\245", 0, QApplication::UnicodeUTF8));
        lbl_chg_time_15->setText(QApplication::translate("p22_ElecPrice_dialog", "\302\245", 0, QApplication::UnicodeUTF8));
        label_t1_1->setText(QApplication::translate("p22_ElecPrice_dialog", "11:30", 0, QApplication::UnicodeUTF8));
        label_t1_2->setText(QApplication::translate("p22_ElecPrice_dialog", "12:30", 0, QApplication::UnicodeUTF8));
        label_p1_1->setText(QApplication::translate("p22_ElecPrice_dialog", "11:30", 0, QApplication::UnicodeUTF8));
        label_p1_2->setText(QApplication::translate("p22_ElecPrice_dialog", "12:30", 0, QApplication::UnicodeUTF8));
        label_f1_1->setText(QApplication::translate("p22_ElecPrice_dialog", "11:30", 0, QApplication::UnicodeUTF8));
        label_f1_2->setText(QApplication::translate("p22_ElecPrice_dialog", "12:30", 0, QApplication::UnicodeUTF8));
        label_g1_1->setText(QApplication::translate("p22_ElecPrice_dialog", "11:30", 0, QApplication::UnicodeUTF8));
        label_g1_2->setText(QApplication::translate("p22_ElecPrice_dialog", "12:30", 0, QApplication::UnicodeUTF8));
        label_f2->setText(QApplication::translate("p22_ElecPrice_dialog", "3", 0, QApplication::UnicodeUTF8));
        label_6->setText(QApplication::translate("p22_ElecPrice_dialog", "~", 0, QApplication::UnicodeUTF8));
        label_7->setText(QApplication::translate("p22_ElecPrice_dialog", "~", 0, QApplication::UnicodeUTF8));
        label_8->setText(QApplication::translate("p22_ElecPrice_dialog", "~", 0, QApplication::UnicodeUTF8));
        label_t2->setText(QApplication::translate("p22_ElecPrice_dialog", "1.2", 0, QApplication::UnicodeUTF8));
        label_p2->setText(QApplication::translate("p22_ElecPrice_dialog", "2", 0, QApplication::UnicodeUTF8));
        label_9->setText(QApplication::translate("p22_ElecPrice_dialog", "~", 0, QApplication::UnicodeUTF8));
        label_g2->setText(QApplication::translate("p22_ElecPrice_dialog", "4", 0, QApplication::UnicodeUTF8));
        lbl_chg_time_16->setText(QApplication::translate("p22_ElecPrice_dialog", "\302\245", 0, QApplication::UnicodeUTF8));
        lbl_chg_time_17->setText(QApplication::translate("p22_ElecPrice_dialog", "\302\245", 0, QApplication::UnicodeUTF8));
        lbl_chg_time_18->setText(QApplication::translate("p22_ElecPrice_dialog", "\302\245", 0, QApplication::UnicodeUTF8));
        lbl_chg_time_19->setText(QApplication::translate("p22_ElecPrice_dialog", "\302\245", 0, QApplication::UnicodeUTF8));
        label_t1_3->setText(QApplication::translate("p22_ElecPrice_dialog", "11:30", 0, QApplication::UnicodeUTF8));
        label_t1_4->setText(QApplication::translate("p22_ElecPrice_dialog", "12:30", 0, QApplication::UnicodeUTF8));
        label_p1_3->setText(QApplication::translate("p22_ElecPrice_dialog", "11:30", 0, QApplication::UnicodeUTF8));
        label_p1_4->setText(QApplication::translate("p22_ElecPrice_dialog", "12:30", 0, QApplication::UnicodeUTF8));
        label_f1_3->setText(QApplication::translate("p22_ElecPrice_dialog", "11:30", 0, QApplication::UnicodeUTF8));
        label_f1_4->setText(QApplication::translate("p22_ElecPrice_dialog", "12:30", 0, QApplication::UnicodeUTF8));
        label_g1_3->setText(QApplication::translate("p22_ElecPrice_dialog", "11:30", 0, QApplication::UnicodeUTF8));
        label_g1_4->setText(QApplication::translate("p22_ElecPrice_dialog", "12:30", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class p22_ElecPrice_dialog: public Ui_p22_ElecPrice_dialog {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_P22_ELECPRICE_DIALOG_H
